<?php declare(strict_types=1); ?>
<section class="hero">
    <div class="hero-glow" aria-hidden="true"></div>
    <div class="shell hero-grid">
        <div class="hero-copy">
            <div class="eyebrow"><?= $icon('graduation-cap') ?><span><?= $e($t('home.hero.eyebrow')) ?></span></div>
            <h1><?= $e($t('home.hero.title')) ?> <span><?= $e($t('home.hero.highlight')) ?></span></h1>
            <p class="hero-lead"><?= $e($t('home.hero.lead')) ?></p>
            <div class="hero-actions"><a class="button button-primary" href="<?= $e($route('product')) ?>"><?= $e($t('actions.explore')) ?><?= $icon('arrow-right') ?></a><a class="button button-secondary" href="<?= $e($demoUrl) ?>" target="_blank" rel="noopener noreferrer"><?= $icon('play') ?><?= $e($t('actions.demo')) ?></a></div>
            <div class="hero-points"><span><?= $icon('check') ?><?= $e($t('home.hero.point_1')) ?></span><span><?= $icon('check') ?><?= $e($t('home.hero.point_2')) ?></span><span><?= $icon('check') ?><?= $e($t('home.hero.point_3')) ?></span></div>
        </div>
        <div class="hero-visual">
            <div class="hero-frame"><picture><source media="(max-width:767px)" srcset="/assets/images/eduvixo-cms-768.webp"><source media="(max-width:1279px)" srcset="/assets/images/eduvixo-cms-1280.webp"><img src="/assets/images/eduvixo-cms-1920.webp" width="1920" height="1080" alt="<?= $e($t('home.hero.image_alt')) ?>" fetchpriority="high"></picture></div>
            <div class="floating-card floating-ai"><?= $icon('sparkles') ?><div><strong><?= $e($t('home.hero.float_ai')) ?></strong><span><?= $e($t('home.hero.float_ai_sub')) ?></span></div></div>
            <div class="floating-card floating-campus"><?= $icon('map-pin') ?><div><strong><?= $e($t('home.hero.float_campus')) ?></strong><span><?= $e($t('home.hero.float_campus_sub')) ?></span></div></div>
        </div>
    </div>
</section>
<section class="trust-bar"><div class="shell trust-grid"><div><?= $icon('shield-check') ?><span><strong><?= $e($t('home.trust.secure')) ?></strong><small><?= $e($t('home.trust.secure_sub')) ?></small></span></div><div><?= $icon('building') ?><span><strong><?= $e($t('home.trust.campus')) ?></strong><small><?= $e($t('home.trust.campus_sub')) ?></small></span></div><div><?= $icon('server') ?><span><strong><?= $e($t('home.trust.hosted')) ?></strong><small><?= $e($t('home.trust.hosted_sub')) ?></small></span></div><div><?= $icon('devices') ?><span><strong><?= $e($t('home.trust.devices')) ?></strong><small><?= $e($t('home.trust.devices_sub')) ?></small></span></div></div></section>
<section class="section intro"><div class="shell narrow center"><span class="section-label"><?= $e($t('home.intro.label')) ?></span><h2><?= $e($t('home.intro.title')) ?></h2><p><?= $e($t('home.intro.copy')) ?></p></div></section>
<?php $ecosystemVariant = 'preview'; require dirname(__DIR__) . '/partials/ecosystem.php'; ?>
<section class="section features"><div class="shell"><div class="section-head"><div><span class="section-label"><?= $e($t('home.features.label')) ?></span><h2><?= $e($t('home.features.title')) ?></h2></div><p><?= $e($t('home.features.copy')) ?></p></div><div class="feature-grid"><?php foreach ((array) $t('home.features.items', []) as $item): ?><article class="feature-card"><div class="feature-icon"><?= $icon((string) ($item['icon'] ?? 'sparkles')) ?></div><h3><?= $e($item['title'] ?? '') ?></h3><p><?= $e($item['copy'] ?? '') ?></p><a href="<?= $e($route('product')) ?>"><?= $e($t('actions.learn')) ?><?= $icon('arrow-right') ?></a></article><?php endforeach; ?></div></div></section>
<section class="section campus-section"><div class="shell campus-grid"><div class="campus-copy"><span class="section-label light"><?= $e($t('home.campus.label')) ?></span><h2><?= $e($t('home.campus.title')) ?></h2><p><?= $e($t('home.campus.copy')) ?></p><ul><li><?= $icon('check') ?><?= $e($t('home.campus.point_1')) ?></li><li><?= $icon('check') ?><?= $e($t('home.campus.point_2')) ?></li><li><?= $icon('check') ?><?= $e($t('home.campus.point_3')) ?></li></ul><a class="text-link light" href="<?= $e($route('product')) ?>"><?= $e($t('home.campus.action')) ?><?= $icon('arrow-right') ?></a></div><div class="campus-flow"><div class="campus-orbit" aria-hidden="true"><i></i><i></i><i></i><span><?= $icon('navigation') ?></span></div><ol><li><b>01</b><span><strong><?= $e($t('home.campus.step_1')) ?></strong><small><?= $e($t('home.campus.step_1_sub')) ?></small></span></li><li><b>02</b><span><strong><?= $e($t('home.campus.step_2')) ?></strong><small><?= $e($t('home.campus.step_2_sub')) ?></small></span></li><li><b>03</b><span><strong><?= $e($t('home.campus.step_3')) ?></strong><small><?= $e($t('home.campus.step_3_sub')) ?></small></span></li></ol></div></div></section>
<section class="section intelligence"><div class="shell intelligence-grid"><div class="intelligence-panel"><span class="section-label"><?= $e($t('home.intelligence.label')) ?></span><h2><?= $e($t('home.intelligence.title')) ?></h2><p><?= $e($t('home.intelligence.copy')) ?></p><div class="intelligence-path"><div><?= $icon('bot') ?><span><strong><?= $e($t('home.intelligence.ai')) ?></strong><small><?= $e($t('home.intelligence.ai_sub')) ?></small></span></div><i><?= $icon('arrow-right') ?></i><div><?= $icon('messages') ?><span><strong><?= $e($t('home.intelligence.human')) ?></strong><small><?= $e($t('home.intelligence.human_sub')) ?></small></span></div></div></div><div class="quote-card"><blockquote>“<?= $e($t('home.intelligence.quote')) ?>”</blockquote><p><?= $e($t('home.intelligence.quote_sub')) ?></p><a class="button button-primary" href="<?= $e($route('services')) ?>"><?= $e($t('actions.services')) ?><?= $icon('arrow-right') ?></a></div></div></section>
<section class="section final-cta"><div class="shell"><div><span class="section-label light"><?= $e($t('home.cta.label')) ?></span><h2><?= $e($t('home.cta.title')) ?></h2><p><?= $e($t('home.cta.copy')) ?></p></div><div><a class="button button-white" href="<?= $e($route('contact')) ?>"><?= $e($t('actions.contact')) ?><?= $icon('arrow-right') ?></a><a class="button button-outline-light" href="<?= $e($demoUrl) ?>" target="_blank" rel="noopener noreferrer"><?= $e($t('actions.demo')) ?><?= $icon('external-link') ?></a></div></div></section>
