<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$root=dirname(__DIR__);$source=$root.'/.cms/source';require $source.'/app/Core/OfficialCatalog.php';
$count=0;$assert=static function(bool$ok,string$label)use(&$count):void{if(!$ok)throw new RuntimeException('FAIL '.$label);$count++;echo 'PASS '.$label.PHP_EOL;};
$release=json_decode((string)file_get_contents($source.'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$assert(($release['channel']??'')==='stable'&&preg_match('/^\d+\.\d+\.\d+$/D',(string)($release['version']??''))===1,'source identifies a Stable semantic release');
$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($root.'/storage/marketplace/official-catalog.json'));$core=$catalog['core']??[];$assert(($core['version']??'')===$release['version']&&($core['engine']??'')===$release['engine']&&($core['channel']??'')==='stable','signed catalog identifies the source release');
$corePath=$root.'/storage/marketplace/packages/eduvixo-core-'.$release['version'].'.zip';$assert(is_file($corePath)&&filesize($corePath)===(int)$core['size']&&hash_equals((string)$core['checksum'],hash_file('sha256',$corePath)),'core archive size and checksum match the signed catalog');
$zip=new ZipArchive();$assert($zip->open($corePath,ZipArchive::RDONLY)===true,'core archive opens');try{$raw=$zip->getFromName('eduvixo-core.json');$signature=base64_decode((string)$zip->getFromName('signature.ed25519'),true);$assert(is_string($raw)&&is_string($signature)&&sodium_crypto_sign_verify_detached($signature,$raw,base64_decode(App\Core\OfficialCatalog::KEY)),'core manifest signature verifies');$manifest=json_decode($raw,true,64,JSON_THROW_ON_ERROR);$assert(($manifest['version']??'')===$release['version']&&($manifest['engine']??'')===$release['engine']&&($manifest['channel']??'')==='stable','core manifest identity is Stable');$assert($zip->numFiles===count($manifest['files']??[])+2,'core archive inventory is complete');foreach((array)($manifest['files']??[])as$path=>$hash){$bytes=$zip->getFromName('payload/'.$path);if(!is_string($bytes)||!hash_equals((string)$hash,hash('sha256',$bytes)))throw new RuntimeException('FAIL core payload integrity: '.$path);}}finally{$zip->close();}$count++;
$market=(static fn($path)=>require$path)($root.'/config/marketplace.php');$system=null;foreach($market['packages']as$item)if(($item['slug']??'')==='eduvixo-cms')$system=$item;$assert(is_array($system)&&($system['version']??'')===$release['version']&&($system['release_channel']??'')==='stable','Marketplace system listing identifies Stable');
$installer=(string)$system['file'];$assert(is_file($installer)&&filesize($installer)===(int)$system['size']&&hash_equals((string)$system['checksum'],hash_file('sha256',$installer)),'clean installer size and checksum match Marketplace');
$zip=new ZipArchive();$assert($zip->open($installer,ZipArchive::RDONLY)===true,'clean installer opens');$files=[];$total=0;try{for($i=0;$i<$zip->numFiles;$i++){$stat=$zip->statIndex($i);$name=(string)$stat['name'];$total+=(int)$stat['size'];if(isset($files[$name])||str_contains($name,'..')||str_starts_with($name,'/')||str_contains($name,'\\'))throw new RuntimeException('FAIL unsafe installer path');$zip->getExternalAttributesIndex($i,$opsys,$attributes);if(($attributes>>16&0170000)===0120000)throw new RuntimeException('FAIL installer symbolic link');$files[$name]=true;}$assert($total<134217728,'clean installer remains within the uncompressed safety limit');foreach(['.htaccess','app/release.json','config/app.php','database/migrations/001_core.sql','public/.htaccess','public/index.php','README.md','storage/.gitkeep','themes/eduvixo/theme.json']as$required)$assert(isset($files[$required]),'installer contains '.$required);$forbidden=array_filter(array_keys($files),static fn(string$name):bool=>$name==='.env'||str_starts_with($name,'.env.')||preg_match('#^(?:\.cfg|\.git/|\.wrk/|packages/|storage/(?!\.gitkeep$))#D',$name)===1||str_contains(strtolower($name),'shoudu'));$assert($forbidden===[],'installer excludes secrets, runtime data and the Shoudu theme');$themes=array_values(array_filter(array_keys($files),static fn(string$name):bool=>preg_match('#^themes/[^/]+/theme\.json$#D',$name)===1));$assert($themes===['themes/eduvixo/theme.json'],'installer bundles only the Eduvixo theme');$embedded=json_decode((string)$zip->getFromName('app/release.json'),true,16,JSON_THROW_ON_ERROR);$assert($embedded===$release,'installer release metadata matches source exactly');}finally{$zip->close();}
foreach($market['packages']as$id=>$item){$artifacts=isset($item['file'])?[$item]:(array)($item['variants']??[]);$assert($artifacts!==[],'Marketplace artifact inventory exists: '.$id);foreach($artifacts as$variant=>$artifact){$path=(string)($artifact['file']??'');$assert(is_file($path)&&filesize($path)===(int)($artifact['size']??-1)&&hash_equals((string)($artifact['checksum']??''),hash_file('sha256',$path)),'Marketplace artifact verifies: '.$id.(is_string($variant)?'/'.$variant:''));}}$assert(count($catalog['products']??[])===count($market['packages']),'signed catalog contains every Marketplace product');
$shape=static function(array$value)use(&$shape):array{$out=[];foreach($value as$key=>$item)$out[$key]=is_array($item)?$shape($item):gettype($item);return$out;};$english=json_decode((string)file_get_contents($root.'/lang/en.json'),true,512,JSON_THROW_ON_ERROR);$expected=$shape($english);foreach(['de','zh','vi','th','lo','pl']as$locale){$copy=json_decode((string)file_get_contents($root.'/lang/'.$locale.'.json'),true,512,JSON_THROW_ON_ERROR);$assert($shape($copy)===$expected,'translation structure matches English: '.$locale);$assert(($copy['updates']['release_date']??'')!==''&&count($copy['updates']['highlights']??[])===6,'Stable release copy is complete: '.$locale);}$assert(!str_contains(implode('',array_map(static fn($locale)=>(string)file_get_contents($root.'/lang/'.$locale.'.json'),['en','de','zh','vi','th','lo','pl'])),'—'),'website copy contains no em dash');
$shell=(string)file_get_contents($source.'/public/theme/eduvixo-shell.js');$assert(str_contains($shell,"querySelector('output[data-text-scale]')")&&!str_contains($shell,"document.querySelector('[data-text-scale]')"),'backend text scale cannot replace the document root');
echo 'Assertions: '.$count.PHP_EOL;
