<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$website='/var/www/clients/client9/web123/web';$package=$website.'/storage/marketplace/packages/eduvixo-calendar-1.1.3.zip';$hash='b63ea96791becb74b654d09829d0f1a055049a5ec908f610c66671efef0f0ead';$tests=0;$assert=static function(bool$ok,string$name)use(&$tests):void{if(!$ok)throw new RuntimeException('FAIL '.$name);$tests++;echo 'PASS '.$name.PHP_EOL;};
$assert(is_file($package)&&filesize($package)===66978&&hash_equals($hash,hash_file('sha256',$package)),'Marketplace package integrity');$market=(static fn(string$path):array=>require$path)($website.'/config/marketplace.php');$item=null;foreach($market['packages']as$product)if(($product['type']??'')==='addon'&&($product['slug']??'')==='calendar')$item=$product;$assert(($item['version']??'')==='1.1.3'&&($item['size']??0)===66978&&hash_equals($hash,(string)($item['checksum']??'')),'Marketplace configuration identity');
require '/var/www/clients/client9/web121/web/app/Core/OfficialCatalog.php';$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($website.'/storage/marketplace/official-catalog.json'));$signed=null;foreach((array)($catalog['products']??[])as$product)if(($product['type']??'')==='addon'&&($product['slug']??'')==='calendar')$signed=$product;$assert(($signed['version']??'')==='1.1.3'&&hash_equals($hash,(string)($signed['package_checksum']??'')),'signed catalogue identity');
foreach(['demo'=>'/var/www/clients/client9/web121/web','shoudu'=>'/var/www/clients/client59/web119/web']as$name=>$root){foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);$config=(static fn(string$path):array=>require$path)($root.'/config/app.php');$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$row=$db->query("SELECT version,active,signature_status,package_checksum FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();if($name==='demo'){$manifest=json_decode((string)file_get_contents($root.'/addons/calendar/addon.json'),true,32,JSON_THROW_ON_ERROR);$dispatcher=(string)file_get_contents($root.'/addons/calendar/src/CalendarDispatcher.php');$assert(($row['version']??'')==='1.1.3'&&(int)($row['active']??0)===1&&($row['signature_status']??'')==='verified'&&hash_equals($hash,(string)($row['package_checksum']??''))&&($manifest['version']??'')==='1.1.3','demo release state');$assert(str_contains($dispatcher,"Description: ")&&str_contains($dispatcher,"format('Y-m-d H:i e')"),'deployed Telegram formatter');}else $assert($row===false&&!is_dir($root.'/addons/calendar'),'Shoudu remains without Calendar');}
foreach(['https://www.eduvixo.com/en/marketplace/'=>200,'https://demo.eduvixo.com/login'=>200,'https://demo.eduvixo.com/calendar'=>302]as$url=>$expected){$curl=curl_init($url);curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_TIMEOUT=>15]);curl_exec($curl);$status=(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE);curl_close($curl);$assert($status===$expected,'HTTP '.$url);}
echo json_encode(['ok'=>true,'tests'=>$tests],JSON_THROW_ON_ERROR).PHP_EOL;
