<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$stage='/root/eduvixo-calendar-1.1.3-candidate';$website='/var/www/clients/client9/web123/web';$package='eduvixo-calendar-1.1.3.zip';$version='1.1.3';$hash='b63ea96791becb74b654d09829d0f1a055049a5ec908f610c66671efef0f0ead';
$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Cannot create destination.');$temp=$target.'.calendar-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publication failed: '.$target);};
$clear=static function():void{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);};$load=static function(string$root)use($clear):array{$clear();return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
foreach([$stage.'/'.$package,$stage.'/marketplace.php',$stage.'/official-catalog.json']as$file)if(!is_file($file))throw new RuntimeException('Incomplete deployment stage.');
if(!hash_equals($hash,hash_file('sha256',$stage.'/'.$package)))throw new RuntimeException('Calendar package checksum failure.');
$market=(static fn(string$path):array=>require$path)($stage.'/marketplace.php');$release=null;foreach($market['packages']as$item)if(($item['type']??'')==='addon'&&($item['slug']??'')==='calendar')$release=$item;
if(!$release||($release['version']??'')!==$version||($release['size']??0)!==filesize($stage.'/'.$package)||!hash_equals($hash,(string)($release['checksum']??'')))throw new RuntimeException('Marketplace Calendar identity failure.');
require $sites[0]['root'].'/app/Core/OfficialCatalog.php';$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($stage.'/official-catalog.json'));$signed=null;foreach((array)($catalog['products']??[])as$product)if(($product['type']??'')==='addon'&&($product['slug']??'')==='calendar')$signed=$product;
if(!$signed||($signed['version']??'')!==$version||!hash_equals($hash,(string)($signed['package_checksum']??'')))throw new RuntimeException('Signed catalog Calendar identity failure.');
$installed=[];foreach($sites as$site){$config=$load($site['root']);$name=(string)$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$name))throw new RuntimeException('Unsafe database name.');$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$name.';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$row=$db->query("SELECT version,active,signature_status FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();$installed[$site['name']]=['site'=>$site,'database'=>$name,'before'=>$row?:null];}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/calendar-telegram-reminder-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create recovery point.');
$run(['tar','-czf',$backup.'/website.tar.gz','-C',$website,'config/marketplace.php','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-calendar-1.1.2.zip']);
foreach($installed as$name=>$entry){if(!$entry['before'])continue;$site=$entry['site'];$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$entry['database']],$backup.'/'.$name.'.sql');$run(['tar','-czf',$backup.'/'.$name.'-calendar.tar.gz','-C',$site['root'],'addons/calendar']);}
foreach(glob($backup.'/*')?:[]as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.$file);echo 'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
foreach($installed as$name=>$entry){if(!$entry['before']){echo strtoupper($name).' CALENDAR_NOT_INSTALLED'.PHP_EOL;continue;}$site=$entry['site'];$private=$site['root'].'/storage/'.$package;$copy($stage.'/'.$package,$private,$site['owner'],$site['group'],0600);try{$clear();$run(['runuser','-u',$site['owner'],'--','php',$site['root'].'/scripts/extension-package.php','install',$private]);}finally{if(is_file($private))unlink($private);}$config=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$after=$db->query("SELECT version,active,signature_status FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();if(($after['version']??'')!==$version||(int)($after['active']??-1)!==(int)$entry['before']['active']||($after['signature_status']??'')!=='verified')throw new RuntimeException('Installed Calendar verification failed: '.$name);$run(['php','-l',$site['root'].'/addons/calendar/src/CalendarDispatcher.php']);echo json_encode(['site'=>$name,'before'=>$entry['before'],'after'=>$after],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;}
$copy($stage.'/'.$package,$website.'/storage/marketplace/packages/'.$package,'web123','client9');$copy($stage.'/marketplace.php',$website.'/config/marketplace.php','web123','client9');$copy($stage.'/official-catalog.json',$website.'/storage/marketplace/official-catalog.json','web123','client9');
if(!hash_equals($hash,hash_file('sha256',$website.'/storage/marketplace/packages/'.$package)))throw new RuntimeException('Published package verification failed.');$liveMarket=(static fn(string$path):array=>require$path)($website.'/config/marketplace.php');$liveCatalog=App\Core\OfficialCatalog::verify((string)file_get_contents($website.'/storage/marketplace/official-catalog.json'));$liveRelease=null;foreach($liveMarket['packages']as$item)if(($item['type']??'')==='addon'&&($item['slug']??'')==='calendar')$liveRelease=$item;if(($liveRelease['version']??'')!==$version)throw new RuntimeException('Published Marketplace configuration failure.');
echo 'DEPLOYMENT_OK '.$backup.PHP_EOL;
