<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$stage='/root/eduvixo-calendar-1.1.3-candidate';$backup='/root/eduvixo-backups/calendar-telegram-reminder-pre-20260902-002018';$demo='/var/www/clients/client9/web121/web';$shoudu='/var/www/clients/client59/web119/web';
$run=static function(array$command):void{$spec=[0=>['pipe','r'],1=>STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start recovery command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Recovery command failed: '.$command[0]);};$clear=static function():void{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);};$load=static function(string$root)use($clear):array{$clear();return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
$expected=['demo-calendar.tar.gz'=>'b1d9aa7008e23df13ad4540d5ca3526951d3c748e3c976a6b521643314bfab41','demo.sql'=>'4c4de8ae363258aa1f2ab1c9a87546b4369a66ed5ead505776e03c6e2c420166','website.tar.gz'=>'b37c3423d16a9fc2b3089a8a955c9921cfe9d1ff15c2e545a85389757ad071e0'];foreach($expected as$file=>$hash)if(!is_file($backup.'/'.$file)||!hash_equals($hash,hash_file('sha256',$backup.'/'.$file)))throw new RuntimeException('Recovery point integrity failure: '.$file);
$demoConfig=$load($demo);$demoDb=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$demoConfig['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$demoRow=$demoDb->query("SELECT version,package_checksum FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();$demoManifest=json_decode((string)file_get_contents($demo.'/addons/calendar/addon.json'),true,32,JSON_THROW_ON_ERROR);if(($demoRow['version']??'')!=='1.1.2'||($demoManifest['version']??'')!=='1.1.3')throw new RuntimeException('Demo is not in the expected interrupted state.');
$shouduConfig=$load($shoudu);$shouduDb=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$shouduConfig['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$shouduRow=$shouduDb->query("SELECT version,package_checksum FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();if(($shouduRow['version']??'')!=='1.1.3'||is_dir($shoudu.'/addons/calendar'))throw new RuntimeException('Shoudu is not in the expected phantom state.');
$failed=$backup.'/demo-failed-calendar-1.1.3';if(file_exists($failed)||!rename($demo.'/addons/calendar',$failed))throw new RuntimeException('Cannot preserve interrupted demo files.');$run(['tar','-xzf',$backup.'/demo-calendar.tar.gz','-C',$demo]);$run(['chown','-R','web121:client9',$demo.'/addons/calendar']);$restored=json_decode((string)file_get_contents($demo.'/addons/calendar/addon.json'),true,32,JSON_THROW_ON_ERROR);if(($restored['version']??'')!=='1.1.2')throw new RuntimeException('Demo file restoration failed.');
if(!is_dir($stage.'/source/payload')||is_dir($shoudu.'/addons/calendar'))throw new RuntimeException('Phantom cleanup source is unavailable.');$run(['cp','-a',$stage.'/source/payload',$shoudu.'/addons/calendar']);$run(['chown','-R','web119:client59',$shoudu.'/addons/calendar']);$helper=$shoudu.'/storage/calendar-phantom-uninstall.php';if(!copy($stage.'/calendar-phantom-uninstall.php',$helper)||!chmod($helper,0600)||!chown($helper,'web119')||!chgrp($helper,'client59'))throw new RuntimeException('Cannot stage phantom cleanup helper.');try{$clear();$run(['runuser','-u','web119','--','php',$helper,$shoudu]);}finally{if(is_file($helper))unlink($helper);}
$demoConfig=$load($demo);$demoDb=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$demoConfig['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$demoVersion=$demoDb->query("SELECT version FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetchColumn();$shouduConfig=$load($shoudu);$shouduDb=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$shouduConfig['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$phantom=$shouduDb->query("SELECT COUNT(*) FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetchColumn();if($demoVersion!=='1.1.2'||(int)$phantom!==0||is_dir($shoudu.'/addons/calendar'))throw new RuntimeException('Recovery verification failed.');echo 'RECOVERY_OK '.$backup.PHP_EOL;
