<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit("CLI only\n");
$demo='/var/www/clients/client9/web121/web';$web='/var/www/clients/client9/web123/web';$stage='/root/eduvixo-deploy';$stamp=gmdate('Ymd-His');
$packages=[
 'eduvixo-calendar-1.1.0.zip'=>['ee5197c31f8f140525af6edbc1e8c6320d17f515ff908b400d71a9e2fa20bc96','calendar','addon'],
 'google-calendar-1.1.0.zip'=>['349ed7b3325b21844f4b2e5da66bec615bb3bdf65964fceea442d2e316309b08','google-calendar','plugin'],
 'apple-calendar-1.1.0.zip'=>['13dd1f0a6bb0791e173786a0f72a4491a7e138a460ca492462ac81eb61331a0e','apple-calendar','plugin'],
 'microsoft-365-calendar-1.1.0.zip'=>['6fd763fe5d3f12701153d57e44520f3eabb7985fd300f5ab1ebf957377f6cda5','microsoft-365-calendar','plugin'],
];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'w']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Target directory could not be created.');$temporary=$target.'.calendar-stable-'.bin2hex(random_bytes(4));if(!copy($source,$temporary)||!chmod($temporary,$mode)||!chown($temporary,$owner)||!chgrp($temporary,'client9')||!rename($temporary,$target)){@unlink($temporary);throw new RuntimeException('Atomic replacement failed: '.$target);}};
if(realpath($demo)!==$demo||realpath($web)!==$web||!is_file($demo.'/public/index.php')||!is_file($web.'/public/index.php'))throw new RuntimeException('Unexpected deployment roots.');
$public=base64_decode('q+WweIoNkskiUOzyLl80Bc9V2TkBdHXXrtOufSRIg54=',true);if(!is_string($public))throw new RuntimeException('Publisher public key is invalid.');
foreach($packages as$file=>[$hash,$slug,$type]){$path=$stage.'/'.$file;if(!is_file($path)||!hash_equals($hash,hash_file('sha256',$path)))throw new RuntimeException('Package integrity failure: '.$file);$zip=new ZipArchive();if($zip->open($path,ZipArchive::RDONLY)!==true)throw new RuntimeException('Unreadable package: '.$file);$raw=$zip->getFromName('eduvixo-package.json');$signature=base64_decode((string)$zip->getFromName('signature.ed25519'),true);if(!is_string($raw)||!is_string($signature)||!sodium_crypto_sign_verify_detached($signature,$raw,$public))throw new RuntimeException('Publisher signature failure: '.$file);$manifest=json_decode($raw,true,64,JSON_THROW_ON_ERROR);if(($manifest['slug']??'')!==$slug||($manifest['type']??'')!==$type||($manifest['version']??'')!=='1.1.0'||($manifest['release_channel']??'')!=='stable')throw new RuntimeException('Package identity failure: '.$file);foreach((array)($manifest['files']??[])as$name=>$payloadHash){$content=$zip->getFromName('payload/'.$name);if(!is_string($content)||!hash_equals((string)$payloadHash,hash('sha256',$content)))throw new RuntimeException('Package payload failure: '.$file);} $zip->close();}
foreach([$stage.'/marketplace.php',$stage.'/official-catalog.json']as$file)if(!is_file($file))throw new RuntimeException('Missing Marketplace release file.');
$catalogDoc=json_decode((string)file_get_contents($stage.'/official-catalog.json'),true,8,JSON_THROW_ON_ERROR);$catalogPayload=base64_decode((string)($catalogDoc['signed_payload']??''),true);$catalogSignature=base64_decode((string)($catalogDoc['signature']??''),true);if(!is_string($catalogPayload)||!is_string($catalogSignature)||!sodium_crypto_sign_verify_detached($catalogSignature,$catalogPayload,$public))throw new RuntimeException('Official catalog signature failure.');
$backup='/root/eduvixo-backups/calendar-stable-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Backup creation failed.');$config=require $demo.'/config/app.php';$dbName=(string)($config['database']['name']??'');if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Invalid database name.');
$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$dbName],$backup.'/demo.sql');
$demoFiles=array_values(array_filter(['addons/calendar','plugins/google-calendar','plugins/apple-calendar','plugins/microsoft-365-calendar','config/extensions.php'],static fn(string$file):bool=>file_exists($demo.'/'.$file)));$run(array_merge(['tar','-czf',$backup.'/demo-extensions.tar.gz','-C',$demo],$demoFiles));
$webFiles=array_values(array_filter(['config/marketplace.php','storage/marketplace/official-catalog.json'],static fn(string$file):bool=>file_exists($web.'/'.$file)));$run(array_merge(['tar','-czf',$backup.'/website-marketplace.tar.gz','-C',$web],$webFiles));
$rollback="Preserve current database before rollback. Extract demo-extensions.tar.gz into {$demo} and website-marketplace.tar.gz into {$web}; restore web121:client9 and web123:client9 ownership respectively; reload php8.4-fpm; run Calendar worker and health checks. New immutable 1.1.0 package files may remain unused. Restore demo.sql only if file rollback is insufficient and only after preserving newer data.\n";file_put_contents($backup.'/ROLLBACK.txt',$rollback,LOCK_EX);
foreach(glob($backup.'/*')?:[]as$file){chmod($file,0600);if(filesize($file)<50)throw new RuntimeException('Incomplete backup: '.$file);echo basename($file).' '.hash_file('sha256',$file).PHP_EOL;}
foreach(array_keys($packages)as$file)$run(['php','-d','display_errors=1',$demo.'/scripts/extension-package.php','install',$stage.'/'.$file,'--activate']);
$run(['chown','-R','web121:client9',$demo.'/addons/calendar']);foreach(['google-calendar','apple-calendar','microsoft-365-calendar']as$slug)$run(['chown','-R','web121:client9',$demo.'/plugins/'.$slug]);
foreach(array_keys($packages)as$file)$copy($stage.'/'.$file,$web.'/storage/marketplace/packages/'.$file,'web123');$copy($stage.'/marketplace.php',$web.'/config/marketplace.php','web123');$copy($stage.'/official-catalog.json',$web.'/storage/marketplace/official-catalog.json','web123');
$run(['systemctl','reload','php8.4-fpm']);$run(['php','-l',$demo.'/addons/calendar/runtime.php']);$run(['php','-l',$demo.'/addons/calendar/src/CalendarRepository.php']);$run(['runuser','-u','web121','--','php',$demo.'/addons/calendar/scripts/calendar-worker.php',$demo,'50']);foreach(['apache2','php8.4-fpm','cron']as$service)$run(['systemctl','is-active','--quiet',$service]);
$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$dbName.';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$installed=$db->query("SELECT type,slug,version,signature_status,active FROM extension_packages WHERE (type='addon' AND slug='calendar') OR (type='plugin' AND slug IN ('google-calendar','apple-calendar','microsoft-365-calendar')) ORDER BY type,slug")->fetchAll();if(count($installed)!==4)throw new RuntimeException('Installed extension count failure.');foreach($installed as$row)if($row['version']!=='1.1.0'||$row['signature_status']!=='verified'||(int)$row['active']!==1)throw new RuntimeException('Installed extension verification failure: '.$row['slug']);
echo json_encode(['ok'=>true,'backup'=>$backup,'installed'=>$installed],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;
