<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$stage='/root/eduvixo-deploy/chat-single-alert-release';$website='/var/www/clients/client9/web123/web';$version='1.0.14';$coreHash='ad23b541fea090319c96b5e352ee008841cabe5af6c6c8b02071a484edc89261';$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Cannot create destination.');$temp=$target.'.chat-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publication failed: '.$target);};
$clear=static function():void{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);};$load=static function(string$root)use($clear):array{$clear();return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
$required=['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip','.wrk/stable-update-bootstrap.php'];foreach($required as$file)if(!is_file($stage.'/'.$file))throw new RuntimeException('Incomplete deployment stage: '.$file);require$sites[0]['root'].'/app/Core/OfficialCatalog.php';$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($stage.'/storage/marketplace/official-catalog.json'));if(($catalog['core']['version']??'')!==$version||!hash_equals($coreHash,(string)($catalog['core']['checksum']??''))||!hash_equals($coreHash,hash_file('sha256',$stage.'/storage/marketplace/packages/eduvixo-core-'.$version.'.zip')))throw new RuntimeException('Signed release identity failure.');
$state=[];foreach($sites as$site){$cfg=$load($site['root']);$dbName=(string)$cfg['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);if(($release['version']??'')!=='1.0.13')throw new RuntimeException('Unexpected source version: '.$site['name']);$state[$site['name']]=['site'=>$site,'database'=>$dbName];}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/chat-single-alert-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create recovery point.');$run(['tar','-czf',$backup.'/website-marketplace.tar.gz','-C',$website,'config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json']);foreach($state as$name=>$entry){$site=$entry['site'];$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$entry['database']],$backup.'/'.$name.'.sql');$run(['tar','-czf',$backup.'/'.$name.'-files.tar.gz','-C',$site['root'],'app/release.json','app/Core/NotificationDispatcher.php','app/Core/NotificationAudience.php']);}file_put_contents($backup.'/ROLLBACK.txt',"Prefer the core updater recovery archive. For targeted recovery restore each files archive to its matching CMS root and website-marketplace.tar.gz to web123, restore ownership and reload PHP-FPM. Restore SQL only after preserving and reconciling every later write.\n",LOCK_EX);foreach(glob($backup.'/*')?:[]as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.basename($file));echo'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip']as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');foreach($sites as$site){$bootstrap=$site['root'].'/storage/stable-update-bootstrap.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$clear();$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$version]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
foreach($sites as$site){$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$dispatcher=(string)file_get_contents($site['root'].'/app/Core/NotificationDispatcher.php');$audience=(string)file_get_contents($site['root'].'/app/Core/NotificationAudience.php');if(($release['version']??'')!==$version||is_file($site['root'].'/storage/system-updates/maintenance.json')||!str_contains($dispatcher,"'key'=>'chat:'.\$row['conversation_id']")||!str_contains($dispatcher,"JSON_UNQUOTE(JSON_EXTRACT(payload,'$.subject'))=?")||!str_contains($audience,"=== 'queued'"))throw new RuntimeException('Chat alert policy verification failed: '.$site['name']);}
$run(['apache2ctl','configtest']);foreach(['apache2','php8.4-fpm','mariadb','cron']as$service)$run(['systemctl','is-active','--quiet',$service]);$run(['systemctl','reload','php8.4-fpm']);echo'DEPLOYMENT_OK '.$backup.PHP_EOL;
