<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$stage='/root/eduvixo-deploy/core-production';$website='/var/www/clients/client9/web123/web';
$sites=[['root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array $command,?string $output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string $source,string $target,string $owner,string $group,int $mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true))throw new RuntimeException('Cannot create target directory.');$temp=$target.'.core-new';if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publish failed: '.$target);};
$load=static function(string $root):array{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);return(static fn($path)=>require $path)($root.'/config/app.php');};
foreach($sites as $site){$config=$load($site['root']);if(!str_starts_with((string)$config['base_url'],'https://'))throw new RuntimeException('Unexpected installation URL.');}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/core-update-pre-'.$stamp;if(!mkdir($backup,0700))throw new RuntimeException('Cannot create deployment backup.');
foreach($sites as $index=>$site){$config=$load($site['root']);$name=$index===0?'demo':'shoudu';$dbName=$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$dbName],$backup.'/'.$name.'.sql');$run(['tar','-czf',$backup.'/'.$name.'.tar.gz','-C',$site['root'],'.']);}
$run(['tar','-czf',$backup.'/website.tar.gz','-C',$website,'.']);
foreach(glob($backup.'/*') as $file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.$file);echo 'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
$websiteFiles=['app/MarketplaceService.php','app/views/pages/marketplace.php','public/api/marketplace/v1/official/index.php','public/api/marketplace/v1/core-package/index.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-1.0.3.zip'];
foreach($websiteFiles as $file)$copy($stage.'/website/'.$file,$website.'/'.$file,'web123','client9');
foreach([$website.'/public/api/marketplace/v1/official',$website.'/public/api/marketplace/v1/core-package']as$directory){chown($directory,'web123');chgrp($directory,'client9');chmod($directory,0750);}
foreach($sites as $site){foreach(['app/Core/OfficialCatalog.php','app/Core/SystemUpdate.php','app/Core/LicenseService.php','scripts/system-update-worker.php'] as $file)$copy($stage.'/cms/'.$file,$site['root'].'/'.$file,$site['owner'],$site['group']);}
foreach($sites as $index=>$site){$name=$index===0?'demo':'shoudu';$cron="* * * * * {$site['owner']} /usr/bin/php {$site['root']}/scripts/system-update-worker.php >> {$site['root']}/storage/logs/system-update.log 2>&1\n";file_put_contents('/etc/cron.d/eduvixo-core-'.$name,$cron,LOCK_EX);chmod('/etc/cron.d/eduvixo-core-'.$name,0644);}
foreach($sites as $site){$bootstrap=$site['root'].'/storage/system-update-bootstrap.php';$copy($stage.'/system-update-bootstrap.php',$bootstrap,$site['owner'],$site['group']);try{$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],'1.0.3']);}finally{if(is_file($bootstrap))unlink($bootstrap);}$run(['chown','-R',$site['owner'].':'.$site['group'],$site['root'].'/storage/system-updates']);}
foreach($sites as $site){$run(['php','-l',$site['root'].'/public/index.php']);$config=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true);if(($release['version']??'')!=='1.0.3')throw new RuntimeException('Unexpected deployed release.');foreach(['023_demo_user_read_only.sql','024_system_notifications.sql']as$migration){$q=$db->prepare('SELECT 1 FROM migrations WHERE name=?');$q->execute([$migration]);if(!$q->fetchColumn())throw new RuntimeException('Missing migration '.$migration);}if(file_exists($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('Maintenance flag remained after deployment.');}
$demoConfig=$load($sites[0]['root']);$demoDb=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$demoConfig['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$q=$demoDb->prepare("SELECT u.active,u.is_demo,COUNT(DISTINCT CASE WHEN p.slug='system.owner' THEN p.id END) owner_permission FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id AND r.active=1 LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id WHERE LOWER(u.email)=? GROUP BY u.id,u.active,u.is_demo");$q->execute(['mario@chivale.email']);$mario=$q->fetch();if(!$mario||(int)$mario['active']!==1||(int)$mario['is_demo']!==0||(int)$mario['owner_permission']!==1)throw new RuntimeException('Mario owner account invariant failed.');
echo 'DEPLOYMENT_OK '.$backup.PHP_EOL;
