[eduvixo-mariadb-auth]
enabled = true
filter = eduvixo-mariadb-auth
backend = systemd
journalmatch = _SYSTEMD_UNIT=mariadb.service
port = 3306
protocol = tcp
maxretry = 3
findtime = 10m
bantime = 1h
action = ittsp-api
