<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
$stage='/root/eduvixo-deploy/email-access-1.0.19';$website='/var/www/clients/client9/web123/web';$version='1.0.19';$themeVersion='1.1.11';$secretFile=$stage.'/smtp.json';
$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9','theme'=>'eduvixo'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59','theme'=>'shoudu']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Cannot create target directory.');$temp=$target.'.email-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publish failed: '.$target);};
$load=static function(string$root):array{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
if(!is_dir($stage)||!is_file($secretFile))throw new RuntimeException('Deployment stage or protected SMTP configuration is unavailable.');
spl_autoload_register(static function(string$class)use($sites):void{if(str_starts_with($class,'App\\')){$file=$sites[0]['root'].'/app/'.str_replace('\\','/',substr($class,4)).'.php';if(is_file($file))require_once$file;}});$catalogRaw=(string)file_get_contents($stage.'/storage/marketplace/official-catalog.json');$catalog=App\Core\OfficialCatalog::verify($catalogRaw);$core=(array)($catalog['core']??[]);if(($core['version']??'')!==$version||($core['channel']??'')!=='stable')throw new RuntimeException('Unexpected signed Core identity.');
$market=(static fn(string$path):array=>require$path)($stage.'/config/marketplace.php');foreach((array)$market['packages']as$item)foreach(isset($item['file'])?[$item]:(array)($item['variants']??[])as$artifact){$name=basename((string)$artifact['file']);$candidate=is_file($stage.'/storage/marketplace/packages/'.$name)?$stage.'/storage/marketplace/packages/'.$name:$website.'/storage/marketplace/packages/'.$name;if(!is_file($candidate)||filesize($candidate)!==(int)$artifact['size']||!hash_equals((string)$artifact['checksum'],hash_file('sha256',$candidate)))throw new RuntimeException('Marketplace artifact integrity failure: '.$name);}
$themePackage=$stage.'/storage/marketplace/packages/eduvixo-theme-'.$themeVersion.'.zip';if(!is_file($themePackage))throw new RuntimeException('Theme package is unavailable.');
$themes=[];foreach($sites as$site){$config=$load($site['root']);if(!str_starts_with((string)$config['base_url'],'https://'))throw new RuntimeException('Unexpected installation URL.');$db=(new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]));$themes[$site['name']]=(string)$db->query('SELECT slug FROM installed_themes WHERE active=1 LIMIT 1')->fetchColumn();if($themes[$site['name']]!==$site['theme'])throw new RuntimeException('Unexpected active theme before deployment: '.$site['name']);}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/base-cms-1.0.19-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create backup.');foreach($sites as$site){$config=$load($site['root']);$dbName=(string)$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$dbName],$backup.'/'.$site['name'].'.sql');$run(['tar','-czf',$backup.'/'.$site['name'].'.tar.gz','-C',$site['root'],'.']);}$run(['tar','-czf',$backup.'/website.tar.gz','-C',$website,'.']);foreach(glob($backup.'/*')as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.$file);echo'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
try{
    foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip','storage/marketplace/packages/eduvixo-theme-'.$themeVersion.'.zip']as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');
    foreach($sites as$site)$copy($stage.'/cms/app/Core/SystemUpdate.php',$site['root'].'/app/Core/SystemUpdate.php',$site['owner'],$site['group']);
    foreach($sites as$site){$bootstrap=$site['root'].'/storage/stable-update-bootstrap.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$version]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
    foreach($sites as$site){$bootstrap=$site['root'].'/storage/theme-update-bootstrap.php';$privatePackage=$site['root'].'/storage/eduvixo-theme-'.$themeVersion.'.zip';$copy($stage.'/.wrk/theme-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);$copy($themePackage,$privatePackage,$site['owner'],$site['group'],0600);try{$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$privatePackage,$themeVersion,'eduvixo']);}finally{if(is_file($bootstrap))unlink($bootstrap);if(is_file($privatePackage))unlink($privatePackage);}}
    $smtp=json_decode((string)file_get_contents($secretFile),true,16,JSON_THROW_ON_ERROR);if(!is_array($smtp)||empty($smtp['password']))throw new RuntimeException('Protected SMTP configuration is invalid.');$site=$sites[0];$config=$load($site['root']);$db=(new App\Core\Database($config['database']))->connection();$cms=new App\Core\CmsRepository($db,new App\Core\EventBus());$email=new App\Core\EmailSystem($db,$cms,new App\Core\Secrets((string)$config['secrets_key']),$config,(string)$config['base_url']);$actor=(int)$db->query("SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id JOIN role_permissions rp ON rp.role_id=r.id JOIN permissions p ON p.id=rp.permission_id WHERE u.active=1 AND COALESCE(u.is_demo,0)=0 AND p.slug='system.owner' ORDER BY u.id LIMIT 1")->fetchColumn();if(!$actor)throw new RuntimeException('No Owner can authorize E-mail settings.');$email->saveServer($smtp,$actor);$stored=(array)$cms->setting('email_system_settings',[]);$cipher=(string)($stored['server']['password_cipher']??'');$plain=$cipher!==''?(new App\Core\Secrets((string)$config['secrets_key']))->decrypt($cipher):'';if($cipher===''||str_contains((string)json_encode($stored),$smtp['password'])||!hash_equals((string)$smtp['password'],$plain))throw new RuntimeException('SMTP secret storage verification failed.');unset($plain,$smtp);
    foreach($sites as$site){$config=$load($site['root']);$db=(new App\Core\Database($config['database']))->connection();$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);if(($release['version']??'')!==$version||($release['channel']??'')!=='stable'||is_file($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('Core verification failed: '.$site['name']);$q=$db->prepare('SELECT 1 FROM migrations WHERE name=?');$q->execute(['026_email_system.sql']);if(!$q->fetchColumn()||!(bool)$db->query("SHOW TABLES LIKE 'email_action_tokens'")->fetchColumn())throw new RuntimeException('E-mail schema verification failed: '.$site['name']);if((string)$db->query('SELECT slug FROM installed_themes WHERE active=1 LIMIT 1')->fetchColumn()!==$themes[$site['name']])throw new RuntimeException('Active theme changed: '.$site['name']);$manifest=json_decode((string)file_get_contents($site['root'].'/themes/eduvixo/theme.json'),true,16,JSON_THROW_ON_ERROR);if(($manifest['version']??'')!==$themeVersion||!is_file($site['root'].'/themes/eduvixo/assets/images/eduvixo-logo-email.svg'))throw new RuntimeException('E-mail theme asset verification failed: '.$site['name']);$run(['php','-l',$site['root'].'/public/index.php']);}
    $run(['apache2ctl','configtest']);$run(['systemctl','reload','php8.4-fpm']);
}finally{if(is_file($secretFile)){file_put_contents($secretFile,str_repeat('0',max(1,filesize($secretFile))),LOCK_EX);unlink($secretFile);}}
echo'DEPLOYMENT_OK '.$backup.PHP_EOL;
