<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
$stage='/root/eduvixo-deploy/email-test-recipient-1.0.21';$website='/var/www/clients/client9/web123/web';$version='1.0.21';$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9','theme'=>'eduvixo'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59','theme'=>'shoudu']];
$run=static function(array$command):void{$process=proc_open($command,[0=>['pipe','r'],1=>STDOUT,2=>STDERR],$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Command failed: '.$command[0]);};$copy=static function(string$src,string$dst,string$owner,string$group,int$mode=0640):void{if(!is_file($src))throw new RuntimeException('Missing staged file: '.$src);if(!is_dir(dirname($dst))&&!mkdir(dirname($dst),0750,true))throw new RuntimeException('Cannot create directory.');$tmp=$dst.'.email-test-'.bin2hex(random_bytes(4));if(!copy($src,$tmp)||!chmod($tmp,$mode)||!chown($tmp,$owner)||!chgrp($tmp,$group)||!rename($tmp,$dst))throw new RuntimeException('Atomic publish failed.');};$load=static function(string$root):array{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
spl_autoload_register(static function(string$class)use($sites):void{if(str_starts_with($class,'App\\')){$file=$sites[0]['root'].'/app/'.str_replace('\\','/',substr($class,4)).'.php';if(is_file($file))require_once$file;}});$raw=(string)file_get_contents($stage.'/storage/marketplace/official-catalog.json');$catalog=App\Core\OfficialCatalog::verify($raw);$core=(array)$catalog['core'];$coreFile=$stage.'/storage/marketplace/packages/eduvixo-core-'.$version.'.zip';if(($core['version']??'')!==$version||!hash_equals((string)$core['checksum'],hash_file('sha256',$coreFile)))throw new RuntimeException('Signed release verification failed.');$market=(static fn(string$path):array=>require$path)($stage.'/config/marketplace.php');$system=(array)$market['packages']['b843df54f8988bad5b884f54dceb7250'];$installer=$stage.'/storage/marketplace/packages/'.basename((string)$system['file']);if(filesize($installer)!==(int)$system['size']||!hash_equals((string)$system['checksum'],hash_file('sha256',$installer)))throw new RuntimeException('Installer verification failed.');
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/email-test-recipient-1.0.21-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create backup.');foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json']as$file){$dst=$backup.'/'.str_replace('/','_',$file);if(!copy($website.'/'.$file,$dst)||!chmod($dst,0600))throw new RuntimeException('Backup failed.');}foreach($sites as$site){foreach(['app/Core/EmailSystem.php','app/Http/DashboardController.php','app/Views/console-email.php','app/Views/console.php','public/theme/eduvixo-email.js']as$file){$src=$site['root'].'/'.$file;if(!is_file($src))continue;$dst=$backup.'/'.$site['name'].'-'.str_replace('/','_',$file);if(!copy($src,$dst)||!chmod($dst,0600))throw new RuntimeException('Backup failed.');}}
foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip']as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');foreach($sites as$site){$bootstrap=$site['root'].'/storage/stable-update-bootstrap.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$version]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
foreach($sites as$site){$config=$load($site['root']);$db=(new App\Core\Database($config['database']))->connection();$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$view=(string)file_get_contents($site['root'].'/app/Views/console-email.php');$script=(string)file_get_contents($site['root'].'/public/theme/eduvixo-email.js');$controller=(string)file_get_contents($site['root'].'/app/Http/DashboardController.php');if(($release['version']??'')!==$version||!str_contains($view,'name="test_email"')||!str_contains($view,'type="button" data-email-test')||!str_contains($script,"fetch('/system/email/test'")||!str_contains($controller,"\$_POST['test_email']")||(string)$db->query('SELECT slug FROM installed_themes WHERE active=1 LIMIT 1')->fetchColumn()!==$site['theme'])throw new RuntimeException('Production verification failed: '.$site['name']);}
$run(['apache2ctl','configtest']);$run(['systemctl','reload','php8.4-fpm']);echo'DEPLOYMENT_OK '.$backup.PHP_EOL;
