<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$website='/var/www/clients/client9/web123/web';$sites=['demo'=>'/var/www/clients/client9/web121/web','shoudu'=>'/var/www/clients/client59/web119/web'];$assertions=0;
$assert=static function(bool$ok,string$label)use(&$assertions):void{if(!$ok)throw new RuntimeException('FAIL '.$label);$assertions++;echo 'PASS '.$label.PHP_EOL;};
$market=(static fn(string$path):array=>require$path)($website.'/config/marketplace.php');$names=array_column($market['packages'],'name');
foreach(['Base CMS','Eduvixo','Shoudu Custom Theme','My Calendar','Desktop Client for Windows']as$name)$assert(in_array($name,$names,true),'Marketplace lists '.$name);
foreach($market['packages']as$id=>$package)foreach(isset($package['file'])?[$package]:(array)($package['variants']??[])as$artifact){$path=(string)$artifact['file'];$assert(is_file($path)&&filesize($path)===(int)$artifact['size']&&hash_equals((string)$artifact['checksum'],hash_file('sha256',$path)),'artifact integrity '.$id);}
foreach(['en','de','zh','vi','th','lo','pl']as$locale){$json=(string)file_get_contents($website.'/lang/'.$locale.'.json');json_decode($json,true,512,JSON_THROW_ON_ERROR);$assert(!str_contains($json,'Eduvixo Calendar')&&!str_contains($json,'Eduvixo CMS')&&!str_contains($json,'Eduvixo for Windows')&&!str_contains($json,'Shoudu Theme'),'public names are neutral in '.$locale);}
foreach($sites as$name=>$root){foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);$config=(static fn(string$path):array=>require$path)($root.'/config/app.php');$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$release=json_decode((string)file_get_contents($root.'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$assert(($release['version']??'')==='1.0.11'&&($release['channel']??'')==='stable',$name.' runs Base CMS 1.0.11 Stable');$activeTheme=(string)$db->query("SELECT slug FROM installed_themes WHERE active=1 LIMIT 1")->fetchColumn();$assert($activeTheme===($name==='demo'?'eduvixo':'shoudu'),$name.' retained active theme');$bad=(int)$db->query("SELECT COUNT(*) FROM extension_packages WHERE name IN ('Eduvixo Calendar','Eduvixo for Windows','Shoudu','Shoudu Theme','Google Calendar for Eduvixo','Apple Calendar for Eduvixo','Microsoft 365 Calendar for Eduvixo','Telegram Notifications for Eduvixo','WhatsApp Notifications for Eduvixo')")->fetchColumn();$assert($bad===0,$name.' package registry contains no legacy public names');$assert(!is_file($root.'/storage/system-updates/maintenance.json'),$name.' maintenance mode is disabled');}
echo 'Assertions: '.$assertions.PHP_EOL;
