<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$archive='/root/eduvixo-deploy/neutral-naming-1.0.11.tar.gz';$expected=(string)($argv[1]??'');$stage='/root/eduvixo-deploy/neutral-naming-1.0.11';$website='/var/www/clients/client9/web123/web';$version='1.0.11';
$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Cannot create target directory.');$temp=$target.'.neutral-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publish failed: '.$target);};
$load=static function(string$root):array{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
if(!preg_match('/^[a-f0-9]{64}$/D',$expected)||!is_file($archive)||!hash_equals($expected,hash_file('sha256',$archive)))throw new RuntimeException('Deployment archive integrity failure.');
if(is_dir($stage))throw new RuntimeException('Deployment stage already exists.');if(!mkdir($stage,0700,true))throw new RuntimeException('Cannot create deployment stage.');$run(['tar','-xzf',$archive,'-C',$stage]);
require $sites[0]['root'].'/app/Core/OfficialCatalog.php';$raw=(string)file_get_contents($stage.'/storage/marketplace/official-catalog.json');$catalog=App\Core\OfficialCatalog::verify($raw);$core=$catalog['core']??[];if(($core['version']??'')!==$version||($core['channel']??'')!=='stable')throw new RuntimeException('Unexpected signed release identity.');
$market=(static fn(string$path):array=>require$path)($stage.'/config/marketplace.php');foreach($market['packages']as$item)foreach(isset($item['file'])?[$item]:(array)($item['variants']??[])as$artifact){$path=$stage.'/storage/marketplace/packages/'.basename((string)$artifact['file']);$fallback=$website.'/storage/marketplace/packages/'.basename((string)$artifact['file']);$candidate=is_file($path)?$path:$fallback;if(!is_file($candidate)||filesize($candidate)!==(int)$artifact['size']||!hash_equals((string)$artifact['checksum'],hash_file('sha256',$candidate)))throw new RuntimeException('Marketplace artifact integrity failure: '.basename($candidate));}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/base-cms-1.0.11-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create backup.');foreach($sites as$site){$config=$load($site['root']);$dbName=(string)$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$dbName],$backup.'/'.$site['name'].'.sql');$run(['tar','-czf',$backup.'/'.$site['name'].'.tar.gz','-C',$site['root'],'.']);}$run(['tar','-czf',$backup.'/website.tar.gz','-C',$website,'.']);foreach(glob($backup.'/*')as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.$file);echo 'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
$websiteFiles=['app/Site.php','app/views/layout.php','app/views/partials/ecosystem.php','config/marketplace.php','public/sitemap.xml','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json'];foreach(['en','de','zh','vi','th','lo','pl']as$locale)$websiteFiles[]='lang/'.$locale.'.json';foreach(glob($stage.'/storage/marketplace/packages/*')as$file)$websiteFiles[]='storage/marketplace/packages/'.basename($file);foreach(array_unique($websiteFiles)as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');
foreach($sites as$site){$bootstrap=$site['root'].'/storage/neutral-update-bootstrap.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$version]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
foreach($sites as$site){$packageDir=$site['root'].'/storage/neutral-packages';if(is_dir($packageDir))throw new RuntimeException('Private package stage already exists: '.$site['name']);if(!mkdir($packageDir,0700,true)||!chown($packageDir,$site['owner'])||!chgrp($packageDir,$site['group']))throw new RuntimeException('Cannot create private package stage.');foreach(glob($stage.'/storage/marketplace/packages/*.zip')as$file){if(str_contains(basename($file),'eduvixo-core-')||str_contains(basename($file),'eduvixo-install-'))continue;$copy($file,$packageDir.'/'.basename($file),$site['owner'],$site['group'],0600);}$helper=$site['root'].'/storage/neutral-extension-update.php';$copy($stage.'/.wrk/neutral-naming-extension-update.php',$helper,$site['owner'],$site['group'],0600);try{$run(['runuser','-u',$site['owner'],'--','php',$helper,$site['root'],$packageDir]);}finally{if(is_file($helper))unlink($helper);foreach(glob($packageDir.'/*')?:[]as$file)unlink($file);rmdir($packageDir);}}
foreach($sites as$site){$config=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);if(($release['version']??'')!==$version||is_file($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('Core verification failed: '.$site['name']);$rows=$db->query("SELECT slug,name,version,active FROM extension_packages WHERE slug IN ('eduvixo','shoudu','calendar','google-calendar','apple-calendar','microsoft-365-calendar','telegram-notifications','whatsapp-notifications') ORDER BY slug")->fetchAll(PDO::FETCH_ASSOC);echo json_encode(['site'=>$site['name'],'version'=>$release['version'],'packages'=>$rows],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;}
echo 'DEPLOYMENT_OK '.$backup.PHP_EOL;
