<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$archive=(string)($argv[1]??'');if(!is_file($archive))throw new RuntimeException('Installer archive is unavailable.');
$id=bin2hex(random_bytes(6));$fixture='/root/eduvixo-install-test-'.$id;$database='eduvixo_install_'.$id;$user='eit_'.$id;$password=bin2hex(random_bytes(24));$count=0;$assert=static function(bool$ok,string$label)use(&$count):void{if(!$ok)throw new RuntimeException('FAIL '.$label);$count++;echo 'PASS '.$label.PHP_EOL;};
$admin=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$remove=static function(string$path)use(&$remove):void{if(!str_starts_with($path,'/root/eduvixo-install-test-'))throw new RuntimeException('Unsafe cleanup target.');if(is_dir($path)&&!is_link($path)){foreach(array_diff(scandir($path)?:[],['.','..'])as$name)$remove($path.'/'.$name);if(!rmdir($path))throw new RuntimeException('Cannot remove test directory.');}elseif(is_file($path)||is_link($path)){if(!unlink($path))throw new RuntimeException('Cannot remove test file.');}};
try{
    $zip=new ZipArchive();if($zip->open($archive,ZipArchive::RDONLY)!==true)throw new RuntimeException('Installer archive cannot be opened.');if(!mkdir($fixture,0700)||!$zip->extractTo($fixture))throw new RuntimeException('Installer archive cannot be extracted.');$zip->close();
    $admin->exec("CREATE DATABASE `$database` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$admin->exec("CREATE USER '$user'@'127.0.0.1' IDENTIFIED BY ".$admin->quote($password));$admin->exec("GRANT ALL PRIVILEGES ON `$database`.* TO '$user'@'127.0.0.1'");
    $env=['CMS_ENV'=>'production','CMS_BASE_URL'=>'https://install-test.example.invalid','CMS_DB_HOST'=>'127.0.0.1','CMS_DB_PORT'=>'3306','CMS_DB_NAME'=>$database,'CMS_DB_USER'=>$user,'CMS_DB_PASSWORD'=>$password,'CMS_DEFAULT_LOCALE'=>'en','CMS_SECRET_KEY'=>rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=')];$lines=[];foreach($env as$key=>$value)$lines[]=$key.'='.json_encode($value,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);file_put_contents($fixture.'/.env',implode(PHP_EOL,$lines).PHP_EOL,LOCK_EX);chmod($fixture.'/.env',0600);
    foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);spl_autoload_register(static function(string$class)use($fixture):void{if(str_starts_with($class,'App\\')){$file=$fixture.'/app/'.str_replace('\\','/',substr($class,4)).'.php';if(is_file($file))require_once$file;}});$config=(static fn($path)=>require$path)($fixture.'/config/app.php');
    $service=new App\Installer\InstallerService($fixture);$requirements=$service->requirements();$assert(count(array_filter($requirements,static fn(array$check):bool=>!$check['ok']))===0,'all installer requirements pass');$db=$service->connect($config['database'],true);$assert((int)$db->query('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE()')->fetchColumn()===0,'installer accepts an empty database');
    $applied=(new App\Core\MigrationRunner())->run($db,$fixture.'/database/migrations');(require$fixture.'/database/seeds/eduvixo.php')($db,['name'=>'Stable Test Owner','username'=>'stable-owner','email'=>'stable-owner@example.invalid','password'=>bin2hex(random_bytes(18))]);(require$fixture.'/database/seeds/ai.php')($db,$config);
    $assert(count($applied)===count(glob($fixture.'/database/migrations/*.sql'))&&count($applied)>=25,'every ordered migration is applied');$assert((int)$db->query('SELECT COUNT(*) FROM migrations')->fetchColumn()===count($applied),'migration history is complete');$assert((string)$db->query("SELECT version FROM installed_themes WHERE slug='eduvixo' AND active=1")->fetchColumn()===(string)json_decode((string)file_get_contents($fixture.'/themes/eduvixo/theme.json'),true)['version'],'seeded theme version matches the bundled manifest');$assert((int)$db->query("SELECT COUNT(*) FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.email='stable-owner@example.invalid' AND u.active=1 AND u.is_demo=0 AND r.slug='owner'")->fetchColumn()===1,'initial administrator is an active non-demo Owner');foreach(['notification_events','web_push_subscriptions','extension_packages','extension_package_releases']as$table)$assert((bool)$db->query("SHOW TABLES LIKE '$table'")->fetchColumn(),'production schema contains '.$table);
    $release=json_decode((string)file_get_contents($fixture.'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$assert(($release['version']??'')==='1.0.13'&&($release['channel']??'')==='stable','installed source identifies Base CMS 1.0.13 Stable');$live='/var/www/clients/client9/web121/web';foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);$liveConfig=(static fn($path)=>require$path)($live.'/config/app.php');(new App\Core\LicenseService($liveConfig['license'],$liveConfig['engine_version']))->enforce($liveConfig['base_url']);$assert(true,'production license validation boundary is healthy');
    echo 'Assertions: '.$count.PHP_EOL;
}finally{try{$admin->exec("DROP DATABASE IF EXISTS `$database`");$admin->exec("DROP USER IF EXISTS '$user'@'127.0.0.1'");}finally{if(is_dir($fixture))$remove($fixture);}}
