<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$root=rtrim((string)($argv[1]??''),'/');$version=(string)($argv[2]??'');if(!is_file($root.'/config/app.php')||!preg_match('/^\d+\.\d+\.\d+$/D',$version))throw new RuntimeException('Invalid update target.');
foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);spl_autoload_register(static function(string$class)use($root):void{if(str_starts_with($class,'App\\')){$file=$root.'/app/'.str_replace('\\','/',substr($class,4)).'.php';if(is_file($file))require_once$file;}});$config=(static fn($path)=>require$path)($root.'/config/app.php');$db=(new App\Core\Database($config['database']))->connection();$service=new App\Core\SystemUpdate($db,$root,$config);$service->requestCheck();$service->run();$state=$service->status();
if(($state['latest']['version']??'')!==$version||($state['latest']['channel']??'')!=='stable'||!empty($state['error']))throw new RuntimeException('The verified Stable release is unavailable.');
if($service->version()!==$version){$owner=$db->query("SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.active=1 JOIN role_permissions rp ON rp.role_id=r.id JOIN permissions p ON p.id=rp.permission_id AND p.slug='system.owner' WHERE u.active=1 AND COALESCE(u.is_demo,0)=0 ORDER BY u.id LIMIT 1")->fetchColumn();if(!$owner)throw new RuntimeException('No active non-demo Owner can authorize the update.');$service->requestInstall($version,(int)$owner);$service->run();$state=$service->status();}
$release=json_decode((string)file_get_contents($root.'/app/release.json'),true,16,JSON_THROW_ON_ERROR);if($service->version()!==$version||($release['channel']??'')!=='stable'||($state['job']['status']??'')!=='completed'||is_file($root.'/storage/system-updates/maintenance.json'))throw new RuntimeException('Stable update verification failed.');
foreach(['023_demo_user_read_only.sql','024_system_notifications.sql','025_web_push.sql']as$migration){$check=$db->prepare('SELECT 1 FROM migrations WHERE name=?');$check->execute([$migration]);if(!$check->fetchColumn())throw new RuntimeException('Missing migration: '.$migration);}
echo json_encode(['ok'=>true,'version'=>$service->version(),'channel'=>$release['channel'],'job'=>$state['job']['status'],'recovery'=>$state['job']['recovery']??null],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;
