<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$stage='/root/eduvixo-deploy/stable-release';$website='/var/www/clients/client9/web123/web';$version='1.0.9';$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true))throw new RuntimeException('Cannot create target directory.');$temp=$target.'.stable-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publish failed: '.$target);};
$load=static function(string$root):array{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);return(static fn($path)=>require$path)($root.'/config/app.php');};
require $sites[0]['root'].'/app/Core/OfficialCatalog.php';$raw=(string)file_get_contents($stage.'/website/storage/marketplace/official-catalog.json');$catalog=App\Core\OfficialCatalog::verify($raw);$core=$catalog['core']??[];if(($core['version']??'')!==$version||($core['channel']??'')!=='stable')throw new RuntimeException('Unexpected signed release identity.');foreach(['eduvixo-core-'.$version.'.zip','eduvixo-install-'.$version.'.zip']as$file)if(!is_file($stage.'/website/storage/marketplace/packages/'.$file))throw new RuntimeException('Missing release artifact: '.$file);if(!hash_equals((string)$core['checksum'],hash_file('sha256',$stage.'/website/storage/marketplace/packages/eduvixo-core-'.$version.'.zip')))throw new RuntimeException('Core package integrity failure.');$market=(static fn($path)=>require$path)($stage.'/website/config/marketplace.php');foreach($market['packages']as$item){foreach(isset($item['file'])?[$item]:(array)($item['variants']??[])as$artifact){$path=(string)$artifact['file'];$candidate=is_file($path)?$path:$website.'/storage/marketplace/packages/'.basename($path);if(!is_file($candidate)||!hash_equals((string)$artifact['checksum'],hash_file('sha256',$candidate)))throw new RuntimeException('Marketplace artifact integrity failure.');}}
$themes=[];foreach($sites as$site){$config=$load($site['root']);if(!str_starts_with((string)$config['base_url'],'https://'))throw new RuntimeException('Unexpected installation URL.');$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$themes[$site['name']]=(string)$db->query('SELECT value FROM settings WHERE `key`="active_theme"')->fetchColumn();}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/eduvixo-1.0-stable-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create deployment backup.');foreach($sites as$site){$config=$load($site['root']);$dbName=(string)$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$dbName],$backup.'/'.$site['name'].'.sql');$run(['tar','-czf',$backup.'/'.$site['name'].'.tar.gz','-C',$site['root'],'.']);}$run(['tar','-czf',$backup.'/website.tar.gz','-C',$website,'.']);foreach(glob($backup.'/*')as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.$file);echo 'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
$files=['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip'];foreach(['en','de','zh','vi','th','lo','pl']as$locale)$files[]='lang/'.$locale.'.json';foreach($files as$file)$copy($stage.'/website/'.$file,$website.'/'.$file,'web123','client9');
foreach($sites as$site){$bootstrap=$site['root'].'/storage/stable-update-bootstrap.php';$copy($stage.'/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group']);try{$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$version]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
foreach($sites as$site){$config=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true);if(($release['version']??'')!==$version||($release['channel']??'')!=='stable'||is_file($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('Deployment state failed: '.$site['name']);if((string)$db->query('SELECT value FROM settings WHERE `key`="active_theme"')->fetchColumn()!==$themes[$site['name']])throw new RuntimeException('Active theme changed: '.$site['name']);$pending=(int)$db->query("SELECT COUNT(*) FROM web_push_deliveries WHERE status IN ('pending','retrying')")->fetchColumn();if($pending>100000)throw new RuntimeException('Unexpected Web Push queue size.');}
$demo=$load($sites[0]['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$demo['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$q=$db->prepare("SELECT u.active,u.is_demo,COUNT(DISTINCT CASE WHEN p.slug='system.owner' THEN p.id END) owner_permission FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id AND r.active=1 LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id WHERE LOWER(u.email)=? GROUP BY u.id,u.active,u.is_demo");$q->execute(['mario@chivale.email']);$mario=$q->fetch(PDO::FETCH_ASSOC);if(!$mario||(int)$mario['active']!==1||(int)$mario['is_demo']!==0||(int)$mario['owner_permission']!==1)throw new RuntimeException('Owner account invariant failed.');
echo 'DEPLOYMENT_OK '.$backup.PHP_EOL;
