<?php
declare(strict_types=1);
$previewRoot=dirname(__DIR__).'/.cms/source';$requestPath=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);
if($_SERVER['REQUEST_METHOD']!=='GET'){http_response_code(405);exit;}
if(str_starts_with($requestPath,'/theme/')||str_starts_with($requestPath,'/assets/'))return false;
require $previewRoot.'/app/Core/OfficialCatalog.php';require $previewRoot.'/app/Core/MarketplaceCatalog.php';$catalog=App\Core\OfficialCatalog::verify(file_get_contents(dirname(__DIR__).'/storage/marketplace/official-catalog.json'));
$updateState=['version'=>'1.0.0','latest'=>$catalog['core'],'available'=>true,'checked_at'=>time(),'error'=>null,'job'=>[],'worker_at'=>time(),'products'=>$catalog['products']];
if(isset($_GET['status'])){header('Content-Type: application/json');echo json_encode(['ok'=>true,'data'=>$updateState]);exit;}
$remote=[];foreach($catalog['products']as$product){if(empty($product['installable']))continue;$copy=(array)($product['copy']['en']??[]);$price=(string)($product['pricing']??'free');$remote[]=['official_id'=>$product['id'],'type'=>$product['type'],'slug'=>$product['slug'],'version'=>$product['version'],'release_channel'=>$product['channel'],'publisher'=>'Eduvixo','manifest'=>['name'=>$product['name'],'description'=>$copy['description']??'','icon'=>$product['icon'],'group'=>$product['type']==='theme'?'Presentation themes':($product['type']==='addon'?'Eduvixo add-ons':'Integrations'),'price_model'=>$price,'price_label'=>$copy['meta'][0]??($price==='paid'?'Paid':'Free'),'release_channel'=>$product['channel']]];}
$pluginArchive=dirname(__DIR__).'/storage/marketplace/packages/google-analytics-1.0.0.zip';$zip=new ZipArchive();$zip->open($pluginArchive);$pluginManifest=json_decode((string)$zip->getFromName('payload/plugin.json'),true,64,JSON_THROW_ON_ERROR);$zip->close();$plugins=['google-analytics'=>$pluginManifest];$packages=[['id'=>1,'type'=>'plugin','slug'=>'google-analytics','name'=>$pluginManifest['name'],'description'=>$pluginManifest['description'],'version'=>$pluginManifest['version'],'source'=>'package','active'=>1,'publisher'=>'QUANT Software House','publisher_url'=>'https://www.ittsp.com/','signature_status'=>'verified','manifest'=>$pluginManifest]];$marketplace=App\Core\MarketplaceCatalog::build('1.0',[],$plugins,[],$packages,[],['google-analytics'=>['active'=>1]],$_GET,$remote);
if($requestPath==='/api/marketplace'){header('Content-Type: application/json');echo json_encode(['ok'=>true,'data'=>$marketplace],JSON_UNESCAPED_SLASHES);exit;}
if(!in_array($requestPath,['/system/update','/marketplace'],true)){header('Content-Type: application/json');echo '{"ok":true,"data":{"total":0,"items":[]}}';exit;}
$title='Update';$screen=$requestPath==='/marketplace'?'marketplace':'system-update';$csrf='preview-only';$flash=null;$licenseNotice=null;$sounds=[];$liveChatSettings=[];$accessPermissions=['system.owner'];$currentRoleNames=['Preview'];$extensionNavigation=[];$user=['id'=>0,'name'=>'Local preview','email'=>'preview@example.invalid'];$isDemoUser=false;$showDemoWelcome=false;$liveChatUnread=$formUnread=$surveyUnread=$packageUpdates=$editorialUnread=0;
$officialMarketplace=$updateState;
require $previewRoot.'/app/Views/console.php';
