<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$stage='/root/eduvixo-deploy/telegram-chat-release';$website='/var/www/clients/client9/web123/web';$coreVersion='1.0.13';$calendarVersion='1.1.5';$calendarFile='eduvixo-calendar-'.$calendarVersion.'.zip';$calendarHash='283de002ea521f221fbfa8cb900601c4950029028a86a5a708cc958402ea024e';
$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Cannot create destination.');$temp=$target.'.release-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publication failed: '.$target);};
$clear=static function():void{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);};$load=static function(string$root)use($clear):array{$clear();return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
$required=['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$coreVersion.'.zip','storage/marketplace/packages/eduvixo-install-'.$coreVersion.'.zip','storage/marketplace/packages/'.$calendarFile,'.wrk/stable-update-bootstrap.php'];foreach($required as$file)if(!is_file($stage.'/'.$file))throw new RuntimeException('Incomplete deployment stage: '.$file);
require$sites[0]['root'].'/app/Core/OfficialCatalog.php';$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($stage.'/storage/marketplace/official-catalog.json'));$core=$catalog['core']??[];$calendar=null;foreach((array)($catalog['products']??[])as$product)if(($product['slug']??'')==='calendar')$calendar=$product;
if(($core['version']??'')!==$coreVersion||!hash_equals((string)$core['checksum'],hash_file('sha256',$stage.'/storage/marketplace/packages/eduvixo-core-'.$coreVersion.'.zip'))||($calendar['version']??'')!==$calendarVersion||!hash_equals($calendarHash,(string)($calendar['package_checksum']??''))||!hash_equals($calendarHash,hash_file('sha256',$stage.'/storage/marketplace/packages/'.$calendarFile)))throw new RuntimeException('Signed release identity failure.');
$state=[];foreach($sites as$site){$cfg=$load($site['root']);$dbName=(string)$cfg['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$dbName.';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$calendarRow=$db->query("SELECT version,active,signature_status FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();if(($release['version']??'')!=='1.0.12')throw new RuntimeException('Unexpected core source version: '.$site['name']);if($site['name']==='demo'&&(($calendarRow['version']??'')!=='1.1.4'||(int)($calendarRow['active']??0)!==1))throw new RuntimeException('Unexpected demo Calendar source version.');if($site['name']==='shoudu'&&($calendarRow!==false||is_dir($site['root'].'/addons/calendar')))throw new RuntimeException('Shoudu must remain without Calendar.');$state[$site['name']]=['site'=>$site,'database'=>$dbName,'calendar'=>$calendarRow?:null];}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/telegram-calendar-chat-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create recovery point.');$run(['tar','-czf',$backup.'/website-marketplace.tar.gz','-C',$website,'config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json']);foreach($state as$name=>$entry){$site=$entry['site'];$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$entry['database']],$backup.'/'.$name.'.sql');$paths=['app/release.json','app/Core/AiRepository.php','app/Core/NotificationDispatcher.php'];if($name==='demo')$paths[]='addons/calendar';$run(array_merge(['tar','-czf',$backup.'/'.$name.'-files.tar.gz','-C',$site['root']],$paths));}file_put_contents($backup.'/ROLLBACK.txt',"Prefer the core updater and Calendar package recovery archives. For targeted recovery restore each files archive to its matching CMS root and website-marketplace.tar.gz to web123, then restore ownership and reload PHP-FPM. Restore SQL only after preserving and reconciling every later write.\n",LOCK_EX);foreach(glob($backup.'/*')?:[]as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.basename($file));echo'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$coreVersion.'.zip','storage/marketplace/packages/eduvixo-install-'.$coreVersion.'.zip','storage/marketplace/packages/'.$calendarFile]as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');
foreach($sites as$site){$bootstrap=$site['root'].'/storage/stable-update-bootstrap.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$clear();$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$coreVersion]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
$demo=$sites[0];$private=$demo['root'].'/storage/'.$calendarFile;$copy($stage.'/storage/marketplace/packages/'.$calendarFile,$private,$demo['owner'],$demo['group'],0600);try{$clear();$run(['runuser','-u',$demo['owner'],'--','php',$demo['root'].'/scripts/extension-package.php','install',$private]);}finally{if(is_file($private))unlink($private);}
foreach($sites as$site){$cfg=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$cfg['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);if(($release['version']??'')!==$coreVersion||is_file($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('Core update verification failed: '.$site['name']);$row=$db->query("SELECT version,active,signature_status,package_checksum FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();if($site['name']==='demo'){if(($row['version']??'')!==$calendarVersion||(int)($row['active']??0)!==1||($row['signature_status']??'')!=='verified'||!hash_equals($calendarHash,(string)($row['package_checksum']??'')))throw new RuntimeException('Calendar update verification failed.');$dispatcher=(string)file_get_contents($site['root'].'/addons/calendar/src/CalendarDispatcher.php');if(!str_contains($dispatcher,"implode('+',\$channels)"))throw new RuntimeException('Calendar channel key correction is absent.');}elseif($row!==false||is_dir($site['root'].'/addons/calendar'))throw new RuntimeException('Calendar was installed on Shoudu.');$chat=(string)file_get_contents($site['root'].'/app/Core/NotificationDispatcher.php');$repo=(string)file_get_contents($site['root'].'/app/Core/AiRepository.php');if(!str_contains($chat,'Sender: ')||!str_contains($chat,'Message: ')||str_contains($repo,'A visitor is waiting for human assistance.'))throw new RuntimeException('Chat notification correction is absent: '.$site['name']);}
$run(['apache2ctl','configtest']);foreach(['apache2','php8.4-fpm','mariadb','cron']as$service)$run(['systemctl','is-active','--quiet',$service]);$run(['systemctl','reload','php8.4-fpm']);echo'DEPLOYMENT_OK '.$backup.PHP_EOL;
