<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$stage='/root/eduvixo-deploy/telegram-profile-release-1.0.15';$website='/var/www/clients/client9/web123/web';$coreVersion='1.0.15';$pluginVersion='1.1.0-beta.1';$pluginFile='telegram-notifications-'.$pluginVersion.'.zip';$pluginHash='e74c1233875ba954e4d2d78bc7bd23475daeeb9985b454b57f82dc2d8150c489';
$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Cannot create destination.');$temp=$target.'.release-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publication failed: '.$target);};
$clear=static function():void{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);};$load=static function(string$root)use($clear):array{$clear();return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
$required=['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$coreVersion.'.zip','storage/marketplace/packages/eduvixo-install-'.$coreVersion.'.zip','storage/marketplace/packages/'.$pluginFile,'.wrk/stable-update-bootstrap.php'];foreach($required as$file)if(!is_file($stage.'/'.$file))throw new RuntimeException('Incomplete deployment stage: '.$file);
require$sites[0]['root'].'/app/Core/OfficialCatalog.php';$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($stage.'/storage/marketplace/official-catalog.json'));$core=$catalog['core']??[];$plugin=null;foreach((array)($catalog['products']??[])as$product)if(($product['slug']??'')==='telegram-notifications')$plugin=$product;
if(($core['version']??'')!==$coreVersion||!hash_equals((string)$core['checksum'],hash_file('sha256',$stage.'/storage/marketplace/packages/eduvixo-core-'.$coreVersion.'.zip'))||($plugin['version']??'')!==$pluginVersion||!hash_equals($pluginHash,(string)($plugin['package_checksum']??''))||!hash_equals($pluginHash,hash_file('sha256',$stage.'/storage/marketplace/packages/'.$pluginFile)))throw new RuntimeException('Signed release identity failure.');
$state=[];foreach($sites as$site){$cfg=$load($site['root']);$dbName=(string)$cfg['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$dbName.';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$row=$db->query("SELECT version,active,signature_status FROM extension_packages WHERE type='plugin' AND slug='telegram-notifications'")->fetch();if(($release['version']??'')!=='1.0.14')throw new RuntimeException('Unexpected Base CMS source version: '.$site['name']);if($site['name']==='demo'&&(($row['version']??'')!=='1.0.2-beta.2'||(int)($row['active']??0)!==1))throw new RuntimeException('Unexpected demo Telegram source version.');if($site['name']==='shoudu'&&$row!==false)throw new RuntimeException('Shoudu must remain without Telegram.');$state[$site['name']]=['site'=>$site,'database'=>$dbName];}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/telegram-profile-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create recovery point.');$run(['tar','-czf',$backup.'/website-marketplace.tar.gz','-C',$website,'config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json']);foreach($state as$name=>$entry){$site=$entry['site'];$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$entry['database']],$backup.'/'.$name.'.sql');$paths=['app/release.json','app/Core/NotificationChannels.php','app/Http/NotificationController.php','app/Views/console-notification-settings.php','app/Views/console.php','public/index.php'];foreach(['public/theme/eduvixo-notifications.css','public/theme/eduvixo-notifications.js']as$file)if(is_file($site['root'].'/'.$file))$paths[]=$file;if($name==='demo')$paths[]='plugins/telegram-notifications';$run(array_merge(['tar','-czf',$backup.'/'.$name.'-files.tar.gz','-C',$site['root']],$paths));}file_put_contents($backup.'/ROLLBACK.txt',"Prefer the Base CMS updater and package recovery archives. For targeted recovery restore each site archive to its matching CMS root, remove public/theme/eduvixo-notifications.css and public/theme/eduvixo-notifications.js when they were absent before this release, and restore website-marketplace.tar.gz to web123. Restore SQL only after preserving and reconciling later writes. Reapply documented owners and reload PHP-FPM.\n",LOCK_EX);foreach(glob($backup.'/*')?:[]as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.basename($file));echo'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$coreVersion.'.zip','storage/marketplace/packages/eduvixo-install-'.$coreVersion.'.zip','storage/marketplace/packages/'.$pluginFile]as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');
$demo=$sites[0];$private=$demo['root'].'/storage/'.$pluginFile;$copy($stage.'/storage/marketplace/packages/'.$pluginFile,$private,$demo['owner'],$demo['group'],0600);try{$clear();$run(['runuser','-u',$demo['owner'],'--','php',$demo['root'].'/scripts/extension-package.php','install',$private]);}finally{if(is_file($private))unlink($private);}
foreach($sites as$site){$bootstrap=$site['root'].'/storage/telegram-profile-update.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$clear();$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$coreVersion]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
foreach($sites as$site){$cfg=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$cfg['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);if(($release['version']??'')!==$coreVersion||is_file($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('Base CMS update verification failed: '.$site['name']);$row=$db->query("SELECT version,active,signature_status,package_checksum FROM extension_packages WHERE type='plugin' AND slug='telegram-notifications'")->fetch();if($site['name']==='demo'){if(($row['version']??'')!==$pluginVersion||(int)($row['active']??0)!==1||($row['signature_status']??'')!=='verified'||!hash_equals($pluginHash,(string)($row['package_checksum']??'')))throw new RuntimeException('Telegram update verification failed.');}elseif($row!==false||is_dir($site['root'].'/plugins/telegram-notifications'))throw new RuntimeException('Telegram was installed on Shoudu.');}
$run(['apache2ctl','configtest']);foreach(['apache2','php8.4-fpm','mariadb','cron']as$service)$run(['systemctl','is-active','--quiet',$service]);$run(['systemctl','reload','php8.4-fpm']);echo'DEPLOYMENT_OK '.$backup.PHP_EOL;
