<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit;
$archive='/root/eduvixo-deploy/toast-layer-1.0.12.tar.gz';$expected=(string)($argv[1]??'');$stage='/root/eduvixo-deploy/toast-layer-1.0.12';$website='/var/www/clients/client9/web123/web';$version='1.0.12';
$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$spec=[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR];$process=proc_open($command,$spec,$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true)&&!is_dir(dirname($target)))throw new RuntimeException('Cannot create target directory.');$temp=$target.'.toast-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publish failed: '.$target);};
$load=static function(string$root):array{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
if(!preg_match('/^[a-f0-9]{64}$/D',$expected)||!is_file($archive)||!hash_equals($expected,hash_file('sha256',$archive)))throw new RuntimeException('Deployment archive integrity failure.');
if(is_dir($stage))throw new RuntimeException('Deployment stage already exists.');if(!mkdir($stage,0700,true))throw new RuntimeException('Cannot create deployment stage.');$run(['tar','-xzf',$archive,'-C',$stage]);
require $sites[0]['root'].'/app/Core/OfficialCatalog.php';$raw=(string)file_get_contents($stage.'/storage/marketplace/official-catalog.json');$catalog=App\Core\OfficialCatalog::verify($raw);$core=$catalog['core']??[];if(($core['version']??'')!==$version||($core['channel']??'')!=='stable')throw new RuntimeException('Unexpected signed release identity.');
foreach(['eduvixo-core-'.$version.'.zip','eduvixo-install-'.$version.'.zip']as$file){$path=$stage.'/storage/marketplace/packages/'.$file;if(!is_file($path)||filesize($path)<1000)throw new RuntimeException('Missing release artifact: '.$file);}$coreFile=$stage.'/storage/marketplace/packages/eduvixo-core-'.$version.'.zip';if(!hash_equals((string)$core['checksum'],hash_file('sha256',$coreFile)))throw new RuntimeException('Core package integrity failure.');
$market=(static fn(string$path):array=>require$path)($stage.'/config/marketplace.php');$base=array_values(array_filter($market['packages'],static fn(array$item):bool=>($item['slug']??'')==='eduvixo-cms'))[0]??null;if(!$base||($base['version']??'')!==$version||!hash_equals((string)$base['checksum'],hash_file('sha256',$stage.'/storage/marketplace/packages/'.basename((string)$base['file']))))throw new RuntimeException('Installer catalogue integrity failure.');
$themes=[];foreach($sites as$site){$config=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$themes[$site['name']]=(string)$db->query('SELECT value FROM settings WHERE `key`="active_theme"')->fetchColumn();}
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/base-cms-1.0.12-toast-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create backup.');foreach($sites as$site){$config=$load($site['root']);$dbName=(string)$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$dbName))throw new RuntimeException('Unsafe database name.');$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$dbName],$backup.'/'.$site['name'].'.sql');$run(['tar','-czf',$backup.'/'.$site['name'].'.tar.gz','-C',$site['root'],'.']);}$run(['tar','-czf',$backup.'/website-marketplace.tar.gz','-C',$website,'config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json']);file_put_contents($backup.'/ROLLBACK.txt',"Restore each CMS archive to its matching web root, restore its SQL dump only if file rollback is insufficient, restore website-marketplace.tar.gz to the website root, restore the documented owners, and reload PHP-FPM. Preserve newer data before any SQL restore.\n");foreach(glob($backup.'/*')as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.$file);echo 'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip']as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');
foreach($sites as$site){$bootstrap=$site['root'].'/storage/toast-update-bootstrap.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$version]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
foreach($sites as$site){$config=$load($site['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);$css=(string)file_get_contents($site['root'].'/public/theme/eduvixo-custom.css');$view=(string)file_get_contents($site['root'].'/app/Views/console.php');if(($release['version']??'')!==$version||($release['channel']??'')!=='stable'||is_file($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('Core verification failed: '.$site['name']);if(!str_contains($css,'.eduvixo-toasts{position:fixed;z-index:12050;')||!str_contains($view,'eduvixo-custom.css?v=20260901-toast-layer-1'))throw new RuntimeException('Toast layer verification failed: '.$site['name']);if((string)$db->query('SELECT value FROM settings WHERE `key`="active_theme"')->fetchColumn()!==$themes[$site['name']])throw new RuntimeException('Active theme changed: '.$site['name']);echo json_encode(['site'=>$site['name'],'version'=>$release['version'],'toast_layer'=>12050,'theme'=>$themes[$site['name']]],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;}
echo 'DEPLOYMENT_OK '.$backup.PHP_EOL;
