<?php
declare(strict_types=1);

if(PHP_SAPI!=='cli')exit(1);
$archive='/root/eduvixo-deploy/web-push-release.tar.gz';$website='/var/www/clients/client9/web123/web';
$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$stamp=gmdate('Ymd-His');$stage='/root/eduvixo-deploy/web-push-release-'.$stamp;$backup='/root/eduvixo-backups/web-push-pre-'.$stamp;
$run=static function(array$command,?string$output=null):void{$process=proc_open($command,[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR],$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start command.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Command failed: '.implode(' ',$command));};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);$temporary=$target.'.webpush-'.bin2hex(random_bytes(5));if(!copy($source,$temporary)||!chmod($temporary,$mode)||!chown($temporary,$owner)||!chgrp($temporary,$group)||!rename($temporary,$target))throw new RuntimeException('Atomic publish failed: '.$target);};
$clear=static function():void{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);};
$load=static function(string$root)use($clear):array{$clear();return(static fn(string$path):array=>require$path)($root.'/config/app.php');};
if(!is_file($archive)||!mkdir($stage,0700,true)||!mkdir($backup,0700,true))throw new RuntimeException('Deployment workspace unavailable.');
$run(['tar','-xzf',$archive,'-C',$stage]);
$required=['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-1.0.8.zip','storage/marketplace/packages/eduvixo-calendar-1.1.1.zip','.cms/source/app/Core/OfficialCatalog.php','.cms/source/app/Core/SystemUpdate.php','.wrk/system-update-bootstrap.php'];foreach($required as$file)if(!is_file($stage.'/'.$file))throw new RuntimeException('Incomplete deployment archive: '.$file);
require$stage.'/.cms/source/app/Core/OfficialCatalog.php';$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($stage.'/storage/marketplace/official-catalog.json'));$calendar=array_values(array_filter((array)$catalog['products'],static fn(array$item):bool=>($item['slug']??'')==='calendar'))[0]??[];
if(($catalog['core']['version']??'')!=='1.0.8'||($calendar['version']??'')!=='1.1.1'||!hash_equals((string)$catalog['core']['checksum'],hash_file('sha256',$stage.'/storage/marketplace/packages/eduvixo-core-1.0.8.zip'))||!hash_equals((string)$calendar['package_checksum'],hash_file('sha256',$stage.'/storage/marketplace/packages/eduvixo-calendar-1.1.1.zip')))throw new RuntimeException('Signed release verification failed.');

$run(['tar','-czf',$backup.'/website-marketplace.tar.gz','-C',$website,'config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json']);
foreach($sites as$site){$config=$load($site['root']);$database=(string)$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$database))throw new RuntimeException('Unsafe database identifier.');$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$database],$backup.'/'.$site['name'].'.sql');$run(['tar','-czf',$backup.'/'.$site['name'].'-core.tar.gz','-C',$site['root'],'app/Core/SystemUpdate.php','app/release.json','public/.htaccess']);}
$run(['tar','-czf',$backup.'/demo-calendar.tar.gz','-C',$sites[0]['root'],'addons/calendar']);
file_put_contents($backup.'/ROLLBACK.txt',"Preserve all writes made after this backup. Prefer each installation's storage/system-updates recovery directory for a core-only rollback and PackageManager release history for Calendar. For disaster recovery, restore the matching core/calendar archives and database into an isolated recovery database first; never overwrite newer production data without reconciliation. Restore website Marketplace files if distribution must be reverted, restore site ownership, validate PHP/Apache and then reload PHP-FPM. Additive migration 025 may remain after a file rollback.\n",LOCK_EX);
foreach(glob($backup.'/*')?:[]as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.basename($file));echo'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}

foreach(['config/marketplace.php','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-1.0.8.zip','storage/marketplace/packages/eduvixo-calendar-1.1.1.zip']as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9');
foreach($sites as$site){$copy($stage.'/.cms/source/app/Core/SystemUpdate.php',$site['root'].'/app/Core/SystemUpdate.php',$site['owner'],$site['group'],0644);$bootstrap=$site['root'].'/storage/system-update-bootstrap-1.0.8.php';$copy($stage.'/.wrk/system-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$clear();$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],'1.0.8']);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
$demo=$sites[0];$calendarPackage=$demo['root'].'/storage/eduvixo-calendar-1.1.1.zip';$copy($stage.'/storage/marketplace/packages/eduvixo-calendar-1.1.1.zip',$calendarPackage,$demo['owner'],$demo['group'],0600);try{$clear();$run(['runuser','-u',$demo['owner'],'--','php',$demo['root'].'/scripts/extension-package.php','install',$calendarPackage,'--activate']);}finally{if(is_file($calendarPackage))unlink($calendarPackage);}

foreach($sites as$site){$clear();$run(['runuser','-u',$site['owner'],'--','php',$site['root'].'/scripts/web-push-keygen.php']);$config=$load($site['root']);$database=(string)$config['database']['name'];$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$database.';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,8,JSON_THROW_ON_ERROR);$key=$site['root'].'/storage/private/web-push-vapid.json';$subscriptions=(bool)$db->query("SHOW TABLES LIKE 'web_push_subscriptions'")->fetchColumn();if(($release['version']??'')!=='1.0.8'||!(bool)$db->query("SELECT 1 FROM migrations WHERE name='025_web_push.sql'")->fetchColumn()||!$subscriptions||!is_file($key)||(fileperms($key)&0777)!==0600||fileowner($key)!==fileowner($site['root']))throw new RuntimeException($site['name'].' Web Push verification failed.');foreach(['app/Core/WebPushSubscriptions.php','app/Core/WebPushSender.php','app/Http/WebPushController.php','public/index.php','scripts/notification-worker.php','scripts/web-push-keygen.php']as$file)$run(['php','-l',$site['root'].'/'.$file]);}
$demoConfig=$load($demo['root']);$demoDb=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$demoConfig['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$installed=$demoDb->query("SELECT version,signature_status,active FROM extension_packages WHERE type='addon' AND slug='calendar'")->fetch();if(($installed['version']??'')!=='1.1.1'||($installed['signature_status']??'')!=='verified'||(int)($installed['active']??0)!==1)throw new RuntimeException('Calendar 1.1.1 verification failed.');
$run(['apache2ctl','configtest']);
echo json_encode(['ok'=>true,'core'=>'1.0.8','calendar'=>'1.1.1','backup'=>$backup],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;
