<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
$archive='/root/eduvixo-deploy/whatsapp-onboarding-release.tar.gz';$stage='/root/eduvixo-deploy/whatsapp-onboarding-'.gmdate('Ymd-His');$website='/var/www/clients/client9/web123/web';$version='1.0.10';$plugin='whatsapp-notifications-1.1.0-beta.1.zip';$sites=[['name'=>'demo','root'=>'/var/www/clients/client9/web121/web','owner'=>'web121','group'=>'client9'],['name'=>'shoudu','root'=>'/var/www/clients/client59/web119/web','owner'=>'web119','group'=>'client59']];
$run=static function(array$command,?string$output=null):void{$process=proc_open($command,[0=>['pipe','r'],1=>$output?['file',$output,'wb']:STDOUT,2=>STDERR],$pipes);if(!is_resource($process))throw new RuntimeException('Cannot start deployment process.');fclose($pipes[0]);if(proc_close($process)!==0)throw new RuntimeException('Deployment command failed: '.$command[0]);};
$copy=static function(string$source,string$target,string$owner,string$group,int$mode=0640):void{if(!is_file($source))throw new RuntimeException('Missing staged file: '.$source);if(!is_dir(dirname($target))&&!mkdir(dirname($target),0750,true))throw new RuntimeException('Cannot create target directory.');$temp=$target.'.whatsapp-'.bin2hex(random_bytes(5));if(!copy($source,$temp)||!chmod($temp,$mode)||!chown($temp,$owner)||!chgrp($temp,$group)||!rename($temp,$target))throw new RuntimeException('Atomic publish failed: '.$target);};
$clear=static function():void{foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);};$load=static function(string$root)use($clear):array{$clear();return(static fn(string$file):array=>require$file)($root.'/config/app.php');};
if(!is_file($archive)||!mkdir($stage,0700,true))throw new RuntimeException('Deployment stage is unavailable.');$run(['tar','-xzf',$archive,'-C',$stage]);
$required=['app/Site.php','app/WhatsAppOnboardingService.php','app/views/whatsapp-onboarding.php','config/site.php','config/marketplace.php','public/.htaccess','public/assets/css/site.min.css','public/assets/js/whatsapp-onboarding.js','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip','storage/marketplace/packages/'.$plugin,'.wrk/stable-update-bootstrap.php'];foreach($required as$file)if(!is_file($stage.'/'.$file))throw new RuntimeException('Incomplete deployment archive: '.$file);
require$sites[0]['root'].'/app/Core/OfficialCatalog.php';$catalog=App\Core\OfficialCatalog::verify((string)file_get_contents($stage.'/storage/marketplace/official-catalog.json'));if(($catalog['core']['version']??'')!==$version||!hash_equals((string)$catalog['core']['checksum'],hash_file('sha256',$stage.'/storage/marketplace/packages/eduvixo-core-'.$version.'.zip')))throw new RuntimeException('Signed core release verification failed.');$wa=array_values(array_filter((array)$catalog['products'],static fn(array$item):bool=>($item['slug']??'')==='whatsapp-notifications'))[0]??[];if(($wa['version']??'')!=='1.1.0-beta.1'||!hash_equals((string)($wa['package_checksum']??''),hash_file('sha256',$stage.'/storage/marketplace/packages/'.$plugin)))throw new RuntimeException('Signed WhatsApp package verification failed.');
$stamp=gmdate('Ymd-His');$backup='/root/eduvixo-backups/whatsapp-onboarding-pre-'.$stamp;if(!mkdir($backup,0700,true))throw new RuntimeException('Cannot create deployment backup.');$run(['tar','-czf',$backup.'/website.tar.gz','-C',$website,'.htaccess','app/Site.php','config/site.php','config/marketplace.php','public/.htaccess','public/assets/css/site.min.css','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json']);foreach($sites as$site){$config=$load($site['root']);$database=(string)$config['database']['name'];if(!preg_match('/^[A-Za-z0-9_]+$/D',$database))throw new RuntimeException('Unsafe database name.');$run(['mariadb-dump','--socket=/run/mysqld/mysqld.sock','--user=root','--single-transaction','--routines','--triggers','--databases',$database],$backup.'/'.$site['name'].'.sql');$run(['tar','-czf',$backup.'/'.$site['name'].'.tar.gz','-C',$site['root'],'.']);}file_put_contents($backup.'/ROLLBACK.txt',"Restore the matching CMS archive and SQL dump only after reconciling writes made after this backup. Restore website.tar.gz into the website root; remove newly added WhatsApp onboarding files if reverting the website. Reapply recorded owners, validate Apache/PHP, and keep the older immutable release packages available.\n",LOCK_EX);foreach(glob($backup.'/*')?:[]as$file){chmod($file,0600);if(filesize($file)<100)throw new RuntimeException('Incomplete backup: '.basename($file));echo'BACKUP '.basename($file).' '.filesize($file).' '.hash_file('sha256',$file).PHP_EOL;}
$websiteFiles=['.htaccess','app/Site.php','app/WhatsAppOnboardingService.php','app/views/whatsapp-onboarding.php','config/site.php','config/marketplace.php','public/.htaccess','public/assets/css/site.min.css','public/assets/js/whatsapp-onboarding.js','storage/marketplace/core-release.json','storage/marketplace/official-catalog.json','storage/marketplace/packages/eduvixo-core-'.$version.'.zip','storage/marketplace/packages/eduvixo-install-'.$version.'.zip','storage/marketplace/packages/'.$plugin];foreach($websiteFiles as$file)$copy($stage.'/'.$file,$website.'/'.$file,'web123','client9',str_ends_with($file,'.htaccess')?0644:0640);
foreach($sites as$site){$bootstrap=$site['root'].'/storage/whatsapp-update-bootstrap.php';$copy($stage.'/.wrk/stable-update-bootstrap.php',$bootstrap,$site['owner'],$site['group'],0600);try{$clear();$run(['runuser','-u',$site['owner'],'--','php',$bootstrap,$site['root'],$version]);}finally{if(is_file($bootstrap))unlink($bootstrap);}}
$demo=$sites[0];$package=$demo['root'].'/storage/'.$plugin;$copy($stage.'/storage/marketplace/packages/'.$plugin,$package,$demo['owner'],$demo['group'],0600);try{$clear();$run(['runuser','-u',$demo['owner'],'--','php',$demo['root'].'/scripts/extension-package.php','install',$package,'--activate']);}finally{if(is_file($package))unlink($package);}
$run(['runuser','-u','web123','--','php','-r','require '.var_export($website.'/config/site.php',true).';']);$key=$website.'/storage/.whatsapp-broker-key';if(!is_file($key)||(fileperms($key)&0777)!==0640||fileowner($key)!==fileowner($website))throw new RuntimeException('Central broker key is not secured.');
foreach($sites as$site){$config=$load($site['root']);$release=json_decode((string)file_get_contents($site['root'].'/app/release.json'),true,16,JSON_THROW_ON_ERROR);if(($release['version']??'')!==$version||!is_file($site['root'].'/app/Core/WhatsAppOnboardingClient.php')||!isset($config['integrations']['whatsapp_onboarding_url'])||is_file($site['root'].'/storage/system-updates/maintenance.json'))throw new RuntimeException('CMS verification failed: '.$site['name']);$run(['php','-l',$site['root'].'/app/Core/WhatsAppOnboardingClient.php']);}
$demoConfig=$load($demo['root']);$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$demoConfig['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$installed=$db->query("SELECT version,active,signature_status FROM extension_packages WHERE type='plugin' AND slug='whatsapp-notifications'")->fetch();if(($installed['version']??'')!=='1.1.0-beta.1'||(int)($installed['active']??0)!==1||($installed['signature_status']??'')!=='verified')throw new RuntimeException('WhatsApp plugin verification failed.');
$run(['php','-l',$website.'/app/Site.php']);$run(['php','-l',$website.'/app/WhatsAppOnboardingService.php']);$run(['apache2ctl','configtest']);echo json_encode(['ok'=>true,'core'=>$version,'whatsapp'=>'1.1.0-beta.1','backup'=>$backup],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;
