<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
$website='/var/www/clients/client9/web123/web';$sites=['demo'=>'/var/www/clients/client9/web121/web','shoudu'=>'/var/www/clients/client59/web119/web'];
$env=[];foreach(is_file($website.'/.env')?(file($website.'/.env',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[]):[]as$line){if(str_starts_with(ltrim($line),'#')||!str_contains($line,'='))continue;[$key]=explode('=',$line,2);$env[trim($key)]=true;}
$meta=[];foreach(['SITE_META_WHATSAPP_APP_ID','SITE_META_WHATSAPP_APP_SECRET','SITE_META_WHATSAPP_CONFIG_ID','SITE_META_WHATSAPP_WEBHOOK_TOKEN','SITE_WHATSAPP_BROKER_KEY']as$key)$meta[$key]=isset($env[$key]);
$key=$website.'/storage/.whatsapp-broker-key';$result=['website'=>['root'=>is_dir($website),'meta_configured'=>$meta,'broker'=>is_file($website.'/app/WhatsAppOnboardingService.php'),'broker_key_secured'=>is_file($key)&&(fileperms($key)&0777)===0640&&fileowner($key)===fileowner($website)],'cms'=>[]];
foreach($sites as$name=>$root){foreach(array_keys(getenv())as$key)if(str_starts_with($key,'CMS_'))putenv($key);$config=(static fn(string$file):array=>require$file)($root.'/config/app.php');$db=new PDO('mysql:unix_socket=/run/mysqld/mysqld.sock;dbname='.$config['database']['name'].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$release=json_decode((string)file_get_contents($root.'/app/release.json'),true);$q=$db->query("SELECT version,available_version,active,signature_status,install_path FROM extension_packages WHERE type='plugin' AND slug='whatsapp-notifications' LIMIT 1");$row=$q->fetch()?:null;$manifest=$row&&is_string($row['install_path']??null)&&is_file($root.'/'.$row['install_path'].'/plugin.json')?json_decode((string)file_get_contents($root.'/'.$row['install_path'].'/plugin.json'),true):null;$result['cms'][$name]=['release'=>$release['version']??null,'base_url'=>$config['base_url'],'client'=>is_file($root.'/app/Core/WhatsAppOnboardingClient.php'),'plugin'=>$row,'manifest_version'=>$manifest['version']??null];}
echo json_encode($result,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;
